### ISSUE TITLE
Accessing IsoConnection structure Socket field on server code

### ISSUE THREAD

**Issue by Kazhuu** [mz-automation/libiec61850#100]
If I want to use Linux platform automatic port assignment (use port 0 with `bind()` function). To check which port was assigned by the kernel I need to use `getsockname()` function. Related stackoverflow post [here](https://stackoverflow.com/a/1077305/4330347).

I need to access HAL layer `Socket` structure. So I checked the source to see I can access `IsoClientConnection`  structure on server side no problem. It seems this structure is opaque pointer to `sIsoConnection` structure which itself contains `Socket` field from HAL layer. This opaque pointer is defined in [this](https://github.com/mz-automation/libiec61850/blob/1e993f20b0a54542ac06bd70934f461187ea53eb/src/mms/inc/iso_server.h#L46) file. `sIsoConnection` structure is defined [here](https://github.com/mz-automation/libiec61850/blob/1e993f20b0a54542ac06bd70934f461187ea53eb/src/mms/iso_server/iso_connection.c#L54). I checked included header files and doxygen documentation to see that does library has a function to access `Socket` field but it seems not. Am I understanding this wrong or this is done on purpose to hide implementation details? If yes would it be possible to add functions to access `Socket` structure and it's file descriptor field so I can get assigned port with `getsockname()` function.

I not 100% sure I still have every piece of the puzzle available to pull this off after this. My use case is that I'm developing a client application related to IED MMS communication and I've done simple mock IED server for testing the client application. All client test are executed in parallel so many mock IED servers are started at the same time so automatic port assignment would solve my problems. If this is not possible I need to move port assignment logic to be part of parallel test runner logic somehow.

**Comment by Kazhuu** [comment]
I'd another thought about this I found a another solution to my problem. I implemented sequence with Redis `INCR` and `EXPIRE` for getting next port number. For my purposes this works like a charm and only needed handful of line edits. So I think this issue is not valid anymore.

**Comment by mzillgith** [comment]
Hi. The Socket implementation is an internal detail. It is hidden to API. Port selection is best done in your test application.
