### ISSUE TITLE
Multiple SubNetwork (Communication) support for GSE CBs

### ISSUE THREAD

**Issue by IvanElenskiy** [mz-automation/libiec61850#112]
While trying to create GSE CB for several subnets discovered it's not supported directly. How about creating array of phycoms in GSE CB? Other approach of creating CB for every address seems to break IEC, and code "GSEControlBlock_addPhyComAddress" hints on increasing number, not setting unique.

**Comment by mzillgith** [comment]
Hi,
Not sure if I understood. The GSE CB is only for a single interface/subnet. Actually multiple phycomms would mean sending multiple messages to the same interface. Why not create multiple CBs?

**Comment by IvanElenskiy** [comment]
I mean sending GOOSE messages to several physical interfaces. I have two different physical interfaces, func IedServer_setGooseInterfaceId sets only one interfaceId. Is it worth keeping interfaceId in sMmsGooseControlBlock?

**Comment by mzillgith** [comment]
Yes you are right. Actually the GOOSE publisher integrated into the server allows only a single interface. Keeping the interface ID in the  MmsGooseControlBlock/GSEControlBlock seems to be a good idea. Yet I am not sure how this can be configured on SCL file level.

**Comment by IvanElenskiy** [comment]
I think ConnectedAP corresponds to physical interface and I plan to use GSE element from ConnectedAP to assign CBs to physical interfaces. Maybe we can assign AP to interfaceID from API similar to IedServer_setGooseInterfaceId.

**Comment by vasilieves** [comment]
I need to find a solution to this problem.

**Comment by vasilieves** [comment]
Сan you make support? This function is very necessary!

**Comment by mzillgith** [comment]
I will add support to set the network interface for GOOSE on the GCB level in v1.4.

**Comment by mzillgith** [comment]
In v1.4 branch the interface can be set for each GCB separately using the IedServer_setGooseInterfaceIdEx function.
