### ISSUE TITLE
Incomplete HAL for BSD

### ISSUE THREAD

**Issue by stv0g** [mz-automation/libiec61850#113]
The following functions seem to be missing for the BSD HAL:

- `Socket_checkAsyncConnectState`
- `Socket_connectAsync`

**Comment by mzillgith** [comment]
Thank you for the hint. I am thinking about removing the support for BSD(originally intended for mac os) as there seems no real demand for it. But as you recognized it maybe you are interested in keeping the support?

**Comment by stv0g** [comment]
👆 I have some use for it. I am using it on macOS.
