### ISSUE TITLE
Header API installation is broken in v1.4

### ISSUE THREAD

**Issue by IvanElenskiy** [mz-automation/libiec61850#117]
On branch v1.4 lib api header iec61850_server.h depends on mms_server.h which isn't installed during install step.

**Comment by IvanElenskiy** [comment]
@mzillgith install doesn't work properly, please consider patch applied (added .txt cause github doesn't support patch format).
[0001-Fixed-build-on-branch-v1.4.patch.txt](https://github.com/mz-automation/libiec61850/files/3028145/0001-Fixed-build-on-branch-v1.4.patch.txt)

**Comment by mzillgith** [comment]
Should be fixed with 8991954e3c2e6927118d3d749ea72cc3953ef3d1
