### ISSUE TITLE
segfault on reconnection

### ISSUE THREAD

**Issue by cedricboudinet** [mz-automation/libiec61850#124]
Hello

I noticed that the client crashes with segv after reconnecting a closed connection. It was working with v1.1.1 but seems to crashes since v1.2.
The bug can be reproduced with iec61850_client_example2.c by adding a label before IedConnection_connect (line 68) and a goto statement after IedConnection_close (line 196).

I only tested with debian 64.

Regards
Cedric

**Comment by mzillgith** [comment]
Hi.
Thanks for the bug report. Should be fixed now (in 1.3)

**Comment by cedricboudinet** [comment]
Hi.
It works. Thanks for the fix.
