### ISSUE TITLE
INSTANCE_LOCKED_BY_OTHER_CLIENT

### ISSUE THREAD

**Issue by Daguele** [mz-automation/libiec61850#125]
I'm trying to serve analog measurement data with a particular adaptation of the serve_example2 in libiec61850, but I can't get it because Server response false to a SetURCB......urcb_t.GI. The service error is "INSTANCE_LOCKED_BY_OTHER_CLIENT" but I only have one client. Somebody should help me? any idea why it happend?

**Comment by mzillgith** [comment]
Please provide more information how to reproduce the issue.

**Comment by Daguele** [comment]
Hi Michael, thanks for your interest, but the problem has been solved. I downloaded version 1.4 and adapted one of the examples. Now it works without any problem. Thank you very much for your work, it's awesome.
