### ISSUE TITLE
dynamic library name for win64

### ISSUE THREAD

**Issue by paluke** [mz-automation/libiec61850#129]
'make dynlib' for win32 target creates iec61850.dll file, but for win64 same command creates libiec61850.so
patch for make/target_system.mk:

--- make/target_system.mk    (revision 1895)
+++ make/target_system.mk    (working copy)
@@ -167,7 +167,7 @@
 LDFLAGS += -arch i386
 endif

-ifeq ($(TARGET), WIN32)
+ifdef WINDOWS
 DYN_LIB_NAME = $(LIB_OBJS_DIR)/iec61850.dll
 else

**Comment by mzillgith** [comment]
Thanks. I added your patch.
