### ISSUE TITLE
Buffer report missing

### ISSUE THREAD

**Issue by JianWei8720** [mz-automation/libiec61850#13]
I enable the buffer report, 3 events are triggered at the same time ,but only 2 event reports are  @received,

Thank you

**Comment by mzillgith** [comment]
Can you explain more? Is it a problem of the client or the server side? What type of events? How are the events triggered... How is the stack configured?

**Comment by JianWei8720** [comment]
thanks very much @mzillgith 

I am new to use this lib.
It is a problem of server side.below my operation step.

1. There are 3 relays in my  device. at 16:15 the 3 relays switch on at the same time, then the state value will changed. Normally once the value changed 3 report information should be received, but only 2 messages captured by the wireshark. 
2. I switch on the relaies interval of 1 minute , 3 report message are received correctlly.

since step 2 can create report message ,i think my stack configure and other configure  is correct,
I doubt that if the server cant report 3 or more messages at same time.

**Comment by mzillgith** [comment]
Depending on your report configuration (BufTm)  it could be that you receive only one report containing the three events. But then it is strange that you see 2 and not only 1 message. Maybe these events are not at exactly the same time? How do you update the state values?

**Comment by JianWei8720** [comment]
Hi @mzillgith  can i have your email ? i want show you my configure screenshot ,but  here cant paste the pic.

**Comment by mzillgith** [comment]
Hi. You can send at info@libiec61850.com.
