### ISSUE TITLE
GCB read problem with readAccessHandler

### ISSUE THREAD

**Issue by virfis** [mz-automation/libiec61850#130]
Hi!
I am trying version 1.3.2 and found some problem.
If  CONFIG_IEC61850_SUPPORT_USER_READ_ACCESS_CONTROL == 1 and readAccessHandler used, cannot read information from goose control block. In _iec61850_common.h_ and functions _FunctionalConstraint_toString_ and _FunctionalConstraint_fromString_  not defined  functional constraint for goose control "GO" and mmsReadAccessHandler return DATA_ACCESS_ERROR_OBJECT_ACCESS_UNSUPPORTED. 
file _mms_mapping.c_, line 2479: _FunctionalConstraint_fromString_ return  IEC61850_FC_NONE and below _ModelNode_getChild_ return NULL, because cannot find goose control block as child of LLN0 node.
I modify _iec61850_common.h_ and functions.  Now it works, but is it correct?
[gcb_read_patched_file.zip](https://github.com/mz-automation/libiec61850/files/2918093/gcb_read_patched_file.zip)

**Comment by mzillgith** [comment]
Hi,
Thank you for the patch. It seems to be good. I integrated it into the code.
