### ISSUE TITLE
set addCause from operateHandler

### ISSUE THREAD

**Issue by kosokroll** [mz-automation/libiec61850#139]
Hi! I am trying to setup operateHandler for controlDo with ctlModel = 3 or 4. When operateHandler returns CONTROL_RESULT_FAILED, addCause will be set ADD_CAUSE_UNKNOWN and error will be set CONTROL_ERROR_UNKOWN. Is there a possibility to setup some other addCause and error in that case?

**Comment by mzillgith** [comment]
Hi. In version 1.3 this is not possible. In version 1.4 the server side control callback functions changed and provide the additional _ControlAction_ parameter. Inside the callback function the addCause can be changed with the _ControlAction_setAddCause_ function.

**Comment by kosokroll** [comment]
That what i need. Thanks!

**Comment by mmiacca** [comment]
Hi

I'm writing a simple IED simulator while learning 61850.
I' trying with the following code (with ctlModel = 3) but all 3party clients receive AddCause ADD_CAUSE_UNKNOWN (normal control is running fine), how can i solve or debug this?

ControlHandlerResult controlHandler(ControlAction action, void* parameter, MmsValue* value, bool test)
{

    ........

    ControlAction_setAddCause(iedServer,  ADD_CAUSE_INVALID_POSITION);

    return CONTROL_RESULT_FAILED;
}

Tks in advance
