### ISSUE TITLE
Is ClientReportControlBlock_destroy should be called in client_example_reporting.c 

### ISSUE THREAD

**Issue by mashomee** [mz-automation/libiec61850#148]
There's no `ClientReportControlBlock_destroy`  in this example. 
Is it necessary and if it does, is it better destroying `ClientReportControlBlock` before or after 
the connection it attachted to destoryed ?

**Comment by mzillgith** [comment]
This is already fixed in v1.4 branch.
You can safely call the function after IedConnection is closed.
