### ISSUE TITLE
Invalid use ObjectReference

### ISSUE THREAD

**Issue by alikovvl** [mz-automation/libiec61850#149]
8.1.3.2 ObjectReference
The IEC 61850-7-2 ObjectReference maps to a variable length MMS visible-string. The
maximum size of the visible-string shall be 129 octets.

char daRef[129];
sprintf(daRef, "%s.%s", doRef, daName);

The array must be 130 bytes due to the presence of a terminating zero.

**Comment by mzillgith** [comment]
I guess you mean the code in iec61850_client_example2
