### ISSUE TITLE
 Differences between iec61850_client_example and mms_client_example

### ISSUE THREAD

**Issue by lupupu** [mz-automation/libiec61850#15]
Excuse me. 

What's the difference between iec61850_client_example and mms_client_example? I didn't find a brief description of them.

Thank you very much.
@mzillgith

**Comment by mzillgith** [comment]
Hi,
iec61850_client_example uses the IEC 61850 API and mms_client_example uses the MMS API. The MMS API is a low-level API and can be used to access the MMS stack directly while the IEC 61850 API is a more high-level API and interface to the IEC 61850 services that are on top of the MMS services. When working with with IEC 61850 you should use the IEC 61850 API and the examples starting with iec61850_client...
