### ISSUE TITLE
MmsVariableSpecification_getSize(MmsVariableSpecification* self) returns negative length

### ISSUE THREAD

**Issue by jpeltonen** [mz-automation/libiec61850#150]
Using .NET API and version 1.3.3.0 of the library. For example for MMS_BIT_STRING type I get length -13 when calling Size() method in MmsVariableSpecification class.
value is 0000000000000 below and there is 13 zeros, but the length is -13.

DA/SDO: [ST] AA1E1Q1/LLN0.Beh.q : MMS_BIT_STRING(-13) : 0000000000000

I also get other negative lengths:
DA/SDO: [DC] AA1E1Q1/Q1CSWI1.EnaOpn.d : MMS_VISIBLE_STRING(-255) :

**Comment by mzillgith** [comment]
A negative return value for the types visible string, octet string, or bit string indicates a maximum size of the type. The actual size can be smaller or equal. In this case the -13 means that the bit string can contain 13 bits or less.
