### ISSUE TITLE
How to deal with this error "TCP_USR_TIMEOUT undeclared"?

### ISSUE THREAD

**Issue by StarsNeverGiveUp** [mz-automation/libiec61850#156]
The edition of libiec61850 is 1.3.3 . Maybe the older edition dont use this macro ?

**Comment by mzillgith** [comment]
What linux version are you using? TCP_USER_TIMEOUT seems not to be supported on systems older than kernel version 2.6.37

**Comment by StarsNeverGiveUp** [comment]
This error comes from cross compiling. The CPU is S3C2440. Which crosstool is useful ?

**Comment by StarsNeverGiveUp** [comment]
libiec61850 1.1 doesn't have this error.

**Comment by HarryChen001** [comment]
> The edition of libiec61850 is 1.3.3 . Maybe the older edition dont use this macro ?

hi,have you solve the problem yet? i met the same problem now

**Comment by StarsNeverGiveUp** [comment]
I found that libiec61850 Version (1.1 or 1.4.2.1) does not have this problem. But I don't know why.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mz-automation/libiec61850] How to deal with this error &quot;TCP_USR_TIMEOUT undeclared&quot;? (#156)





  
The edition of libiec61850 is 1.3.3 . Maybe the older edition dont use this macro ?
  
hi,have you solve the problem yet? i met the same problem now

**Comment by HarryChen001** [comment]
> I found that libiec61850 Version (1.1 or 1.4.2.1) does not have this problem. But I don't know why.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月25日(星期四) 中午11:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [mz-automation/libiec61850] How to deal with this error &quot;TCP_USR_TIMEOUT undeclared&quot;? (#156) The edition of libiec61850 is 1.3.3 . Maybe the older edition dont use this macro ? hi,have you solve the problem yet? i met the same problem now — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

i had solved this problem by adding a "#define TCP_USER_TIMEOUT 18" in hal/socket/linux/socket_linux.c
