### ISSUE TITLE
In the icd file，when the data attribute's  btype is Dbpos, genmodel.jar can't work.

### ISSUE THREAD

**Issue by StarsNeverGiveUp** [mz-automation/libiec61850#163]
Warning: Initialization of CODEDENUM is unsupported!
Unknown default value for iedModel_LD001_XSWI_Pos_stVal type: CODEDENUM

In the icd file , the btype of iedModel_LD001_XSWI_Pos_stVal is Dbpos.

Both libiec61850 Ed1.0 and Ed1.3 have this problem.

**Comment by mzillgith** [comment]
This is a process value. I think it shouldn't be initialized by the ICD file but by the real process value when the application is starting?
