### ISSUE TITLE
send error PDU problem

### ISSUE THREAD

**Issue by Mrcbj** [mz-automation/libiec61850#178]
hello!Function encodeReadResponse,line 530,I debugged here, mmsPduSize=87536        connection->maxPduSize=65000.
how to solve this problem!

`    /* Check if message would fit in the MMS PDU */
    if (mmsPduSize > connection->maxPduSize) {
        if (DEBUG_MMS_SERVER)
            printf("MMS read: message to large! send error PDU!	mmsPduSize=%d	connection->maxPduSize=%d\n",mmsPduSize,connection->maxPduSize);

        mmsMsg_createServiceErrorPdu(invokeId, response,
                MMS_ERROR_SERVICE_OTHER);

        goto exit_function;
    }`

I tried to modify this macro definition (CONFIG_MMS_MAXIMUM_PDU_SIZE), but it seems that this macro definition does not take effect.

**Comment by mzillgith** [comment]
The maximum PDU size is negotiated betwenn client and server when the connection is established. If you change the parameter CONFIG_MMS_MAXIMUM_PDU_SIZE this only effects the maximum size that is supported by the library. But the other side has to support this size also. In practice it is very uncommon to have larger sizes than 65000. So your application should not depend on larger PDU sizes.

**Comment by Mrcbj** [comment]
> The maximum PDU size is negotiated betwenn client and server when the connection is established. If you change the parameter CONFIG_MMS_MAXIMUM_PDU_SIZE this only effects the maximum size that is supported by the library. But the other side has to support this size also. In practice it is very uncommon to have larger sizes than 65000. So your application should not depend on larger PDU sizes.

Now, my model is running in the Libiec61850 library, and there have been cases where the mmsPduSize is greater than 65000. In addition, I made DEBUG_MMS_SERVER equal to 1, and received "MMS getVariableAccessAttributes: message to large! send error PDU!", what is the cause of this!

**Comment by Mrcbj** [comment]
> The maximum PDU size is negotiated betwenn client and server when the connection is established. If you change the parameter CONFIG_MMS_MAXIMUM_PDU_SIZE this only effects the maximum size that is supported by the library. But the other side has to support this size also. In practice it is very uncommon to have larger sizes than 65000. So your application should not depend on larger PDU sizes.

Now, my model is running in the Libiec61850 library, and there have been cases where the mmsPduSize is greater than 65000. In addition, I made DEBUG_MMS_SERVER equal to 1, and received "MMS getVariableAccessAttributes: message to large! send error PDU!", what is the cause of this! Can you give me some advice?

**Comment by mzillgith** [comment]
I guess your data model is very large and the request is for a top level element in the data model tree. The client has to change the request so that the response can fit into the MMS PDU.

**Comment by Mrcbj** [comment]
> I guess your data model is very large and the request is for a top level element in the data model tree. The client has to change the request so that the response can fit into the MMS PDU.

Yes, I have already negotiated this issue with the client. Thank you!
