### ISSUE TITLE
Difference between the time it takes to maintain a connection between win32 and linux

### ISSUE THREAD

**Issue by alikovvl** [mz-automation/libiec61850#18]
In linux, 5s + 2s * 2 = 9s.
In win32 5s + 2s = 7s.

**Comment by mzillgith** [comment]
I don't understand what that means. Is is about the TCP keep alive?

**Comment by alikovvl** [comment]
Yes

**Comment by mzillgith** [comment]
In windows the third parameter (number of repeated TCP keep alive messages when no ACK is received) can not be set by the program. It depends on a system wide registry setting (see https://msdn.microsoft.com/en-us/library/Dd877220(v=VS.85).aspx )
