### ISSUE TITLE
Misspelled function name

### ISSUE THREAD

**Issue by Jojinon** [mz-automation/libiec61850#180]
Function name should be
```IedServer_updateDbposValue```

The function does not seem to be used anywhere so changing should not cause any problems except for people who already uses it in their projects!

Declared at:
https://github.com/mz-automation/libiec61850/blob/6f7df75d85786b0e169ea007be959a51159a83cb/src/iec61850/inc/iec61850_server.h#L861

Defined at:
https://github.com/mz-automation/libiec61850/blob/6f7df75d85786b0e169ea007be959a51159a83cb/src/iec61850/server/impl/ied_server.c#L1056

**Comment by mzillgith** [comment]
Thanks. I fixed it.
