### ISSUE TITLE
BufferReportControl not handler

### ISSUE THREAD

**Issue by ttgzs** [mz-automation/libiec61850#185]
libiec61850:1.4 latest
platform:win 10 x64
build env:vs2017 winx64 build && cmake  install
application: .net core 2.2
=======================
1.IEC61850 Client Connect IEC61850 Server
2. rcb1.GetRCBValues();
3.InstallReportHandler
4.rcb.SetRCBValues();
5.ChangeServer dataset fdca value,but reporthandler no received data
6.I try to change libiec61850 from 1.4 to 1.2, It's ok; try to change libiec61850 from 1.4 to 1.3 ,it's ok.
7.so ,I think 1.4 exits bug;

**Comment by mzillgith** [comment]
I cannot reproduce this issue. When I try the report examples from the "dotnet" solution they work fine with this configuration.

**Comment by ttgzs** [comment]
> I cannot reproduce this issue. When I try the report examples from the "dotnet" solution they work fine with this configuration.

I build the latest 1.4 lib, .net native lib is 1.4 ,I want get data from reportHandler event,but I can't any data from reportType is BRCB. but reference lib 1.2 ,I can get data from reportHandler event.
`using System;
using System.Threading;

using IEC61850.Client;
using IEC61850.Common;

namespace reporting
{
    class ReportingExample
	{

		private static void reportHandler (Report report, object parameter)
		{
			Console.WriteLine ("Received report:\n----------------");

			Console.WriteLine ("  for RCB: " + report.GetRcbReference());

			if (report.HasTimestamp ())
				Console.WriteLine ("  timestamp: " + MmsValue.MsTimeToDateTimeOffset (report.GetTimestamp ()).ToString ());

			MmsValue values = report.GetDataSetValues ();

			byte[] entryId = report.GetEntryId ();

			if (entryId != null) {
                Console.WriteLine ("  entryID: " + BitConverter.ToString(entryId));
			}

			if (report.HasDataSetName ()) {
				Console.WriteLine ("   report data set: " + report.GetDataSetName ());
			}

			Console.WriteLine ("  report dataset contains " + values.Size () + " elements");

			for (int i = 0; i < values.Size(); i++) {
				if (report.GetReasonForInclusion(i) != ReasonForInclusion.REASON_NOT_INCLUDED) {
					Console.WriteLine("    element " + i + " included for reason " + report.GetReasonForInclusion(i).ToString() + " " + values.GetElement(i));
				}

                if (report.HasDataReference()) {
                    Console.WriteLine("       data-ref: " + report.GetDataReference(i));
                }
                
			}

			ReportControlBlock rcb = (ReportControlBlock) parameter;
            
			Console.WriteLine("  For RCB: " + rcb.GetObjectReference() + " Buffered: " + rcb.IsBuffered() +
			                  " data-set: " + rcb.GetDataSetReference ());
           
		}


		private static bool running = true;

		public static void Main (string[] args)
		{
			IedConnection con = new IedConnection ();

			string hostname;

			if (args.Length > 0)
				hostname = args [0];
			else
				hostname = "localhost";

			Console.WriteLine ("Connect to " + hostname);

			try {
				con.Connect (hostname, 102);

				//string rcbReference1 = "PNC_IEDMONT/LLN0.RP.urcbds01Measure01";
				//string rcbReference2 = "PNC_IEDMONT/LLN0.RP.brcbds01Pulse01";
				string rcbReference3 = "PNC_IEDMONT/LLN0.BR.brcbds01State01";

				//ReportControlBlock rcb1 = con.GetReportControlBlock(rcbReference1);
				//ReportControlBlock rcb2 = con.GetReportControlBlock(rcbReference2);
				ReportControlBlock rcb3 = con.GetReportControlBlock(rcbReference3);

                //rcb1.GetRCBValues();

                //// note: the second parameter is not required!
                //rcb1.InstallReportHandler(reportHandler, rcb1);

                //if (rcb1.IsBuffered())
                //    Console.WriteLine("RCB: " + rcbReference1 + " is buffered");

                //rcb1.SetTrgOps(TriggerOptions.DATA_CHANGED | TriggerOptions.INTEGRITY);
                //rcb1.SetIntgPd(5000);
                //rcb1.SetRptEna(true);

                //rcb2.GetRCBValues();

                //if (rcb2.IsBuffered())
                //    Console.WriteLine("RCB: " + rcbReference2 + " is buffered");

                //rcb2.InstallReportHandler(reportHandler, rcb2);

                //rcb2.SetOptFlds(ReportOptions.REASON_FOR_INCLUSION | ReportOptions.SEQ_NUM | ReportOptions.TIME_STAMP |
                //    ReportOptions.CONF_REV | ReportOptions.ENTRY_ID | ReportOptions.DATA_REFERENCE | ReportOptions.DATA_SET);
                //rcb2.SetTrgOps(TriggerOptions.DATA_CHANGED | TriggerOptions.INTEGRITY);
                //rcb2.SetIntgPd(2000);
                //rcb2.SetRptEna(true);

                //rcb2.SetRCBValues();

                //rcb2.GetRCBValues();

                //Console.WriteLine("RCB: " + rcbReference2 + " Owner: " + BitConverter.ToString(rcb2.GetOwner()));

				rcb3.GetRCBValues();

				if (rcb3.IsBuffered())
					Console.WriteLine ("RCB: " + rcbReference3 + " is buffered");

				rcb3.InstallReportHandler(reportHandler, rcb3);
               
                rcb3.SetOptFlds(ReportOptions.REASON_FOR_INCLUSION | ReportOptions.SEQ_NUM | ReportOptions.TIME_STAMP |
                                ReportOptions.CONF_REV | ReportOptions.ENTRY_ID | ReportOptions.DATA_REFERENCE | ReportOptions.DATA_SET);
                rcb3.SetTrgOps(TriggerOptions.DATA_CHANGED | TriggerOptions.INTEGRITY);				
				rcb3.SetIntgPd(2000);
				rcb3.SetRptEna(true);

				rcb3.SetRCBValues();


				/* run until Ctrl-C is pressed */
				Console.CancelKeyPress += delegate(object sender, ConsoleCancelEventArgs e) {
					e.Cancel = true;
					ReportingExample.running = false;
				};

				/* stop main loop when connection is lost */
				con.InstallConnectionClosedHandler(delegate(IedConnection connection) {
					Console.WriteLine("Connection closed");
					ReportingExample.running = false;
				});

				while (running) {
					Thread.Sleep(10);
				}

				/* Dispose the RCBs when you no longer need them */
				//rcb1.Dispose();
				//rcb2.Dispose();
				rcb3.Dispose();

				con.Abort ();

				con.Dispose();
			} catch (IedConnectionException e) {
				Console.WriteLine ("Error: " + e.Message);

				con.Dispose ();
			}

		}
	}
}
`
icd file [https://github.com/ttgzs/iedexplorer/blob/master/IEC61850(1).icd](url)

**Comment by mzillgith** [comment]
I have no idea what could be the problem in your case. When I try your model I can receive reports.

**Comment by umutklc** [comment]
any update on this topic? I am having similar issue with lib 1.4.

 @ttgzs  did you get any solution for  your problem?

**Comment by mzillgith** [comment]
@umutklc What are the exact issues you have? On what platform does the issues occur?
