### ISSUE TITLE
Not found FileSystem_openFile in .net core lib

### ISSUE THREAD

**Issue by ttgzs** [mz-automation/libiec61850#186]
I want to write IecServer demo,but I find the IECModel createModelFromConfigFile Error.
tip `{"Unable to find an entry point named 'FileSystem_openFile' in DLL 'iec61850'.":""}`
then I depends dll,not found FileSystem_openFile,.
1.2 &1.3 is exits filesystem_openfile.

` public class ConfigFileParser
        {

            [DllImport("iec61850", CallingConvention = CallingConvention.Cdecl)]
            static extern IntPtr FileSystem_openFile(string filePath, [MarshalAs(UnmanagedType.I1)] bool readWrite);

            [DllImport("iec61850", CallingConvention = CallingConvention.Cdecl)]
            static extern IntPtr ConfigFileParser_createModelFromConfigFile(IntPtr fileHandle);

            public static IedModel CreateModelFromConfigFile(string filePath)
            {
                try
                {
                    
                    IntPtr fileHandle = FileSystem_openFile (filePath, false);

                    if (fileHandle != IntPtr.Zero)
                    {

                        IntPtr retVal = ConfigFileParser_createModelFromConfigFile((IntPtr)fileHandle.ToInt32());
                        if (retVal == IntPtr.Zero)
                        {
                            return null;
                        }

                        return new IedModel(retVal);

                    }
                    else
                        return null;
                }
                catch (Exception ex)
                {

                    throw ex;
                }

                //TODO else throw exception
            }
        }`

**Comment by JonathanFortier-eaton** [comment]
I have the same problem here with .NET Framework lib v1.4.0... 
Seems related to the way functions are exported from the C library DLL. 
In v1.3.3, a .DEF file was used to list all functions to export from the DLL, while in v1.4.0, the lib rely only on "__declspec(dllexport)". 
In the case of FileSystem-related functions, PAL_API should be responsible to define "__declspec(dllexport)", but it seems ignored for unknown reasons...

**Comment by ttgzs** [comment]
Have you solved your problem

> I have the same problem here with .NET Framework lib v1.4.0...
> Seems related to the way functions are exported from the C library DLL.
> In v1.3.3, a .DEF file was used to list all functions to export from the DLL, while in v1.4.0, the lib rely only on "__declspec(dllexport)".
> In the case of FileSystem-related functions, PAL_API should be responsible to define "__declspec(dllexport)", but it seems ignored for unknown reasons...

**Comment by JonathanFortier-eaton** [comment]
> Have you solved your problem
> 
> > I have the same problem here with .NET Framework lib v1.4.0...
> > Seems related to the way functions are exported from the C library DLL.
> > In v1.3.3, a .DEF file was used to list all functions to export from the DLL, while in v1.4.0, the lib rely only on "__declspec(dllexport)".
> > In the case of FileSystem-related functions, PAL_API should be responsible to define "__declspec(dllexport)", but it seems ignored for unknown reasons...

No, but you can use v1.3.3 until the issue is fixed...

**Comment by mzillgith** [comment]
The idea with v1.4 was to hide some library internals like the file system access. I didn't recognize that it breaks this function. I think I will add a new function ConfigFileParser_createModelFromConfigFileEx that accepts the filename as string parameter instead of the file handle and can be used by the .net api.

**Comment by JonathanFortier-eaton** [comment]
Make sense... 
I guess the old ConfigFileParser_createModelFromConfigFile will not be useful anymore from outside the shared lib/DLL if we can't create a FileHandle with the exposed functions...

**Comment by mzillgith** [comment]
Now it should work again from .NET. But you need to rebuild the native library so that the new function ConfigFileParser_createModelFromConfigFileEx is available.
