### ISSUE TITLE
Compilation of the C libraries fails with VS2012

### ISSUE THREAD

**Issue by JonathanFortier-eaton** [mz-automation/libiec61850#189]
When using Visual Studio 2012 to compile v1.4.0 C libraries, the compilation of iec61850/iec61850-shared projects fails because "bool" type is not defined in the C compiler of that version.
Normally, we force C++ compilation of C files to circumvent that problem, but this is not done for "lib_asn1c_SRCS" because this breaks compilation.
Another way to fix the problem would be to define bool in  "src/vs/stdbool.h" to make sure bool is defined in C for older compilers...

**Comment by mzillgith** [comment]
Please check this patch https://github.com/mz-automation/libiec61850/commit/16c7124c2bdbde5b67453239e6a142ef98fda15a. 
It should solve the issue (at least it did for me with VS 2010).

**Comment by JonathanFortier-eaton** [comment]
Thanks!
Your patch [16c7124](https://github.com/mz-automation/libiec61850/commit/16c7124c2bdbde5b67453239e6a142ef98fda15a) targeted VS2010 and older, but by changing the _MSC_VER version to 1700, it does fix the problem! 
Note that bool support for C compiler was introduced in VS2013, as can be seen in this [link](https://devblogs.microsoft.com/cppblog/c99-library-support-in-visual-studio-2013/), so I think 1700 is the correct version to use.

As an alternative, I also managed to fix the problem by putting the `#define bool int` inside "src/vs/stdbool.h". I think this solution is better, since the goal of that file is to define bool, and that local copy should only be used by non-C99-conformant compilers (no need to check for _MSC_VER).

**Comment by mzillgith** [comment]
I finally did it as you suggested (added "define bool" to "src/vs/stdbool.h"). It works with VS2010.
