### ISSUE TITLE
Memory leak in SV publisher

### ISSUE THREAD

**Issue by maxim133** [mz-automation/libiec61850#191]
SV publisher doesn't have function for delete SVPublisher_ASDU. Memory for SVPublisher_ASDU is reserved in the function SVPublisher_addASDU.

**Comment by maxim133** [comment]
Also ethernetSocket in the struct sSVPublisher not deleted anywhere.

**Comment by mzillgith** [comment]
Thanks for the bug report! Should be fixed now.
