### ISSUE TITLE
Reoport Subscribe Stoped

### ISSUE THREAD

**Issue by hu-jin-cheng** [mz-automation/libiec61850#192]
1.writevalue error when not found node, ReportHandler never received data.
2.FC enum append error,eg snapshot
![image](https://user-images.githubusercontent.com/40563090/70133368-e6cdcb80-16c0-11ea-99da-67d4716b9f46.png)

**Comment by mzillgith** [comment]
1) I don't fully understand what you mean. But you shouldn't call WriteValue in the report handler. That might cause dead-locks. The report handler is only for handling the received report data.
2) In object references you cannot use "$" as separator. You should use "."

**Comment by ttgzs** [comment]
Thank you，you are right！

**Comment by hu-jin-cheng** [comment]
Thank you very much for your answer
