### ISSUE TITLE
sqNum not reset to 0 when stNum is inscreased

### ISSUE THREAD

**Issue by si-gr** [mz-automation/libiec61850#199]
As specified on page 90 in the norm

> sqNum
This INTEGER value shall have a range of 0 to 4 294 967 295. Following a StNum change, the counter SqNum shall be set to 0. If the counter SqNum overruns it shall be set to 1.

sqNum is correctly reset to 0 but increased before sending the packet:

https://github.com/mz-automation/libiec61850/blob/8c1b75b382a7aa45918b850bf6f801de83cc0a4c/src/goose/goose_publisher.c#L390

**Comment by mzillgith** [comment]
Yes you are right. It is increased before sending but after encoding the message. So at this point it has no more influence on the sent value and is correct. What is not correct is the overflow behaviour as it is set to 0 in case of overflow instead of 1 as you mentioned above.

**Comment by si-gr** [comment]
oh, true... Thank you for the quick answer and your fix of the (other) bug.
