### ISSUE TITLE
server_example_logging cannot  generate log

### ISSUE THREAD

**Issue by liwei6797** [mz-automation/libiec61850#2]
I build server_example_logging project with vs2010，and run the server_example_logging.exe，but there is no record in the log_status.db. Please help.
![image](https://cloud.githubusercontent.com/assets/5889026/23647461/ec6cc0ea-0350-11e7-8aae-5aaffee2161f.png)

![image](https://cloud.githubusercontent.com/assets/5889026/23647435/caa780f8-0350-11e7-91a9-40551c71db65.png)

![image](https://cloud.githubusercontent.com/assets/5889026/23647420/b16a8450-0350-11e7-88f7-b3a705fea6be.png)

**Comment by mzillgith** [comment]
Did you trigger the log? (Changing some of the data attributes that are in the data set of the log control block)
If you use the example as it is it will only log when you change the GGIO1.SPCSOx controls.

**Comment by Uskok** [comment]
Hi,
Writing to database is disabled in code by default. Change "#if 0" to "#if 1" (4 times).
Regards,

    Boris

**Comment by mzillgith** [comment]
@Uskok the disabled code in the example is only to illustrate how to write some arbitrary content to the database manually. This is not the standard way (therefore it is out commented - maybe there should be added an explanation in the examples source code).  The actual code of the log service to write to the database is inside the library and will only be executed when the defined trigger conditions (as specified in the LCB and the data model) are met.
