### ISSUE TITLE
Control operate not working (ADD_CAUSE_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#20]
Hello,

This is a nice project and I am trying to use it.

I have this IED:

![image](https://user-images.githubusercontent.com/3512138/31843645-fd2e6994-b5d2-11e7-93aa-9b10d3a70f73.png)

**I am trying to operate a command:**

                IedConnection iedConnection = new IedConnection();
                iedConnection.Connect("192.168.0.125", "102");

                switch (controlModel)
                {
                    case ControlModel.STATUS_ONLY:
                        Console.WriteLine("Control is status-only!");
                        break;

                    case ControlModel.DIRECT_NORMAL:
                    case ControlModel.DIRECT_ENHANCED:
                        if (control.Operate(true))
                            Console.WriteLine("operated successfully!");
                        else
                            Console.WriteLine("operate failed!");
                        break;

                    case ControlModel.SBO_NORMAL:
                    case ControlModel.SBO_ENHANCED:
                        if (control.Operate(false))
                            Console.WriteLine("operated successfully!");
                        else
                            Console.WriteLine("operate failed!");

                        LastApplError error = control.GetLastApplError();

                        break;
                }

                iedConnection.Abort();
                iedConnection.Dispose();

**I get error: ADD_CAUSE_NOT_SUPPORTED**

**What am I doing wrong?**

**Comment by mzillgith** [comment]
I think there is nothing wrong. It just means that the server provides no additional information about a problem (if there is any).
But when using SBO control you have to use the proper select (Select/SelectWithValue) before operate.

**Comment by IgorMundstein** [comment]
@mzillgith 

**Sorry, I forgot to say...**

**Select/SelectWithValue commands does not work either.**

```
if (control.Select()) {
	if (control.Operate(false))
		Console.WriteLine("operated successfully!");
	else
		Console.WriteLine("operate failed!");							
}
else
	Console.WriteLine("Select failed!");
	
if (control.SelectWithValue(true)) {
	if (control.Operate(false))
		Console.WriteLine("operated successfully!");
	else
		Console.WriteLine("operate failed!");							
}
else
	Console.WriteLine("Select failed!");
```

**I get "Select failed" on both examples.**

**Comment by mzillgith** [comment]
And what is the value of ctlModel?

**Comment by mzillgith** [comment]
It would be good if you could post some wireshark captures to see what actually happens.

**Comment by IgorMundstein** [comment]
@mzillgith 

> And what is the value of ctlModel?

**The value can be seen in the image. I also tried the exchange between values (True/False).**

> It would be good if you could post some wireshark captures to see what actually happens.

CO structure:
![image](https://user-images.githubusercontent.com/3512138/31903221-46047c96-b806-11e7-9622-426d33604e51.png)

The command **control.GetControlModel()** returns **ControlModel.SBO_ENHANCED**

**[Test on IED (SIEMENS)]**

Wireshark 
Filter: ip.addr == 192.168.0.125 && tcp.port == 102 && mms
**Logs (.pcapng files):** https://ufile.io/fll9m

Select Command (FAILED):
![image](https://user-images.githubusercontent.com/3512138/31907606-19c3a94c-b813-11e7-88ad-98bb12dad047.png)
![image](https://user-images.githubusercontent.com/3512138/31907636-273ef9d2-b813-11e7-8cfb-b4362f831e65.png)

Select Command with Value (FAILED):
![image](https://user-images.githubusercontent.com/3512138/31907660-3875da5e-b813-11e7-9ff1-a9a933e806a0.png)
![image](https://user-images.githubusercontent.com/3512138/31907670-3f01132a-b813-11e7-960c-5f2591ef7cb9.png)
![image](https://user-images.githubusercontent.com/3512138/31907674-43628bd8-b813-11e7-9d7e-c871d8f8ce48.png)

Operate (without select) (FAILED):
![image](https://user-images.githubusercontent.com/3512138/31907439-92d0f3fe-b812-11e7-9ec4-a56bd62211f9.png)
![image](https://user-images.githubusercontent.com/3512138/31907410-80438c56-b812-11e7-9965-d54bd7f47866.png)
![image](https://user-images.githubusercontent.com/3512138/31907447-97abcbf6-b812-11e7-8563-d3b7443faf3a.png)


**Note:** I was able to test the library on a simulator (https://www.infotech.pl/iec-61850/libraries/tip-iec-61850-browser-61850-avenue-tip) that uses the both versions of the protocol. This IED (SIEMENS) uses the firmware protocol in version 1. Would that be a problem or limitation? 

[Test on IED SIMULATOR (INFOTECH)]

Wireshark 
Filter: ip.addr == 192.168.0.108 && tcp.port == 102 && mms
Log (.pcapng file): https://ufile.io/iuhi9

Select Command with Value + Operate (SUCCESS):
![image](https://user-images.githubusercontent.com/3512138/31908135-ad93dc04-b814-11e7-9d22-096508b2a63b.png)
![image](https://user-images.githubusercontent.com/3512138/31908141-b195b50c-b814-11e7-8917-e68e7578005a.png)
![image](https://user-images.githubusercontent.com/3512138/31908147-b646499a-b814-11e7-9fa9-1d1724a987d8.png)

**Comment by mzillgith** [comment]
Ok. That information helps to get closer to the problem.

**Comment by IgorMundstein** [comment]
@mzillgith 

OMG. That makes sense.

I used the command: control.SetOrigin("192.168.0.100", OrCat.REMOTE_CONTROL);
before control.SelectWithValue / control.Operate

It works!

Thank you so much.

**Comment by mzillgith** [comment]
Nice to hear that it works :-)
