### ISSUE TITLE
Problem in Server between 1.3.2 and 1.4.1

### ISSUE THREAD

**Issue by Morand84** [mz-automation/libiec61850#207]
I'm using windows 10 64 bit , Visual Studio 2013 compiler and I'm building a IEC 61850 server project. 
The 1.3.2 version still works perfectly , but in 1.4.1 I've found that servers (including all servers in the examples) do not accept incoming socket connections anymore.
Even the connection handler callback it's not called anymore when I try to connect.. 
Maybe .. is there some parameter that I need to change in stak_config.h ? 
Thanks.

**Comment by mzillgith** [comment]
There has been a bug in the windows socket handling that has been revealed by a library refactoring. Your problem should be fixed with commit 37d43fe8d40ff72875978d7a55c03bea8ef2038a

**Comment by Morand84** [comment]
Yes, now it works fine.
