### ISSUE TITLE
Add context to IED Server update value methods

### ISSUE THREAD

**Issue by andy1547** [mz-automation/libiec61850#209]
Opendnp3 allows supplying a EventMode parameter which influences the behaviour when updating values:
````
enum class EventMode : uint8_t
{
  /// Detect events using the specific mechanism for that type
  Detect = 0x0,
  /// Force the creation of an event bypassing detection mechanism
  Force = 0x1,
  /// Never produce an event regardless of changes
  Suppress = 0x2,
  /// Send an event directly to the event buffer, bypassing the static value completely
  EventOnly = 0x3
};
// https://github.com/dnp3/opendnp3/blob/2.3.2/cpp/libs/include/opendnp3/gen/EventMode.h
````
What's particularly useful is the Suppress and EventOnly options:
Suppress -  is useful for startup where you're only interested in updating the current status but don't want this update to trigger an event to be sent.
EventOnly - is useful for sending historic events but you don't want these events to change the current status.

In libiec61850 updates to the attributes cause the current status to be updated and a report to be generated.

Implementing the Suppress option could be done by skipping the checkForChangedTriggers/checkForUpdateTrigger calls.

Implementing the EventOnly option is debatable, it could be argued that the Log Service should be used to report historical values. The client may not be expect timestamps to go backwards when using RCBs/Goose. Another complication is knowing what flag to set when calling MmsMapping_triggerReportObservers as it would be impossible to know whether the historic value triggered an update/change. This is further complicated if the Dataset entry references a DataObject, as the values for the dependent DataAttributes which are not receiving the historical update would be unknown when generating the report.

**Comment by mzillgith** [comment]
For initialization you can just call the _IedServer_updateAttributeValue_ function before you call the _IedServer_start_ function. 

There is also another way doing that. Please see the following code:
```
MmsValue* value = IedServer_getAttributeValue(iedServer, IEDMODEL_GenericIO_GGIO1_DPCSO1_stVal);
MmsValue_setBitStringFromInteger(value, 1);
```
Regarding the _EventOnly_ option I see no useful application. In particular it would confuse the sequence of events that  is expected by report or GOOSE subscribers. If the requirement is not loosing events then the buffered report or log service should be used.

**Comment by andy1547** [comment]
Calling IedServer_updateAttributeValue before server startup works for URCBs, however for BRCBs a report is generated which is unexpected.

The MmsValue_setBitStringFromInteger method looks like a good workaround, I'll do some testing and get back to you on this.

**Comment by andy1547** [comment]
Set methods worked a treat, closing.
