### ISSUE TITLE
dotnet wrapper gives heap corruption when disposing structure with children

### ISSUE THREAD

**Issue by pergardebrink** [mz-automation/libiec61850#213]
When running the following code, the program terminates before the console writeline because it gets a heap corruption (0xc0000374).
```
var parent = MmsValue.NewEmptyStructure(1);
var child = MmsValue.NewEmptyStructure(1);
parent.SetElement(0, child);
child.Dispose();
parent.Dispose();
Console.WriteLine("The end");
```

I have a proposed solution that fixes this in a pull request: https://github.com/mz-automation/libiec61850/pull/212

**Comment by mzillgith** [comment]
Thanks for the hint! Should be fixed now

**Comment by pergardebrink** [comment]
Thank you!
