### ISSUE TITLE
stack_config.h missing from installed headers

### ISSUE THREAD

**Issue by aaribaud** [mz-automation/libiec61850#214]
PR https://github.com/mz-automation/libiec61850/commit/8991954e3c2e6927118d3d749ea72cc3953ef3d1 removed `stack_config.h` from the installed headers despite the fact that it is `#include`d by installed header `libiec61850_platform_includes.h`.

This makes it impossible to compile applications which assume a minimal "devel" setup where the libiec61850 compiled libraries and headers has been installed with `sudo make install`.

**Comment by mzillgith** [comment]
Thanks for the hint. I removed some more header files I consider internal from the install target.

**Comment by aaribaud** [comment]
Ok, so I'll close https://github.com/mz-automation/libiec61850/pull/215 then

**Comment by aaribaud** [comment]
BTW same fix is needed on v1.5
