### ISSUE TITLE
Problem parsing variables in "parseJournalVariable @ mms_client_journals.c" 

### ISSUE THREAD

**Issue by matias-martini** [mz-automation/libiec61850#224]
Hello Michael, 
I was working on a new LogHandler to keep track of all the activities happening in the mms-server. After a few minutes, I managed to get the server working, but then I got stuck dealing with the client. 
Every time I requested a log entry from a client, I managed to receive an entry with a valid variableTag but a (null) valueSpec. (Tried the examples and got the same result).

After a few coffees reading the code and recompiling the library, I think I found a silver lining. 
When the client is decoding the Mms_data from the buffer in the "parseJournalVariable" method @ "mms_client_journals.c", it seems that the "endBufPos" entered is not the real end position of the buffer but the length of the data to read.

`journalVariable->value = MmsValue_decodeMmsData(buffer, bufPos,length, NULL);` 

This caused the parser to fail  (**bufPos<maxBufPos**), returning -1 from BerDecoder_decodeLength and then NULL from MmsValue_decodeMmsData.

I managed to get it working by changing the last mentioned line for 
`journalVariable->value = MmsValue_decodeMmsData(buffer, bufPos, bufPos+length, NULL);`

Could it be a solution?

Thanks for your work.

**Comment by mzillgith** [comment]
Thanks for your hint! You are absolutely right and your suggested fix solves the issue.
