### ISSUE TITLE
set automatic disconnection after timeout

### ISSUE THREAD

**Issue by Mrcbj** [mz-automation/libiec61850#226]
Hello, I want to ask how to set the timeout period of mms as a server? At present, I run the code on an embedded device, the CPU runs slower, and IEDScout connection timeout often occurs. IEDScout indicates that the connection to the server was cancelled due to timeout, and then the device fell into a certain endless loop

**Comment by mzillgith** [comment]
What do you mean with timeout period of the server? I guess you need to increase the timeout of IEDScout?
