### ISSUE TITLE
XCBR position issue

### ISSUE THREAD

**Issue by Adambrin** [mz-automation/libiec61850#229]
Hello MichaeI,

I have been testing  libiec61850 few days now and i couldn't read the XCBR position. Depending on the position i normaly should get a returned value either: 01; 10 ; 00 or  11.  In my case i always get 10 what ever the position is. Bellow the code i'm using. Can you help?
/* Check if status value has changed */ 
  MmsValue* stVal = IedConnection_readObject(con, &error, "ABB1LD0/CB2XCBR1.Pos.stVal", IEC61850_FC_ST);
  if (error == IED_ERROR_OK) {
   bool state = MmsValue_getBoolean(stVal);
   MmsValue_delete(stVal);
   
   printf("New status of AQL399_1LD0/CB2XCBR1.Pos.stVal : %i\n", state);
  }
  else {
   printf("Reading status for AQL399_1LD0/CB2XCBR1.Pos.stVal failed!\n");
  }

Thank you

**Comment by mzillgith** [comment]
I think it is because you are assuming that stVal is boolean (using the MmsValue_getBoolean function). But it isn't.

**Comment by Adambrin** [comment]
What would be the right  code to read xcbr position properly, can you suggest any?

**Comment by Adambrin** [comment]
Thank you, problem solved.
