### ISSUE TITLE
[C# API] CreateControlObject throws System.AccessViolationException on Dispose

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#23]
Hi,

I realized that I get an error when I use the command **IedConnection.Dispose()** after **ControlObject.CreateControlObject()**. 

The error only occurs when I use **ControlObject.CreateControlObject()**. 
However, the command was executed successfully.

![image](https://user-images.githubusercontent.com/3512138/31967702-720895e2-b8ed-11e7-886a-8f355b3323f3.png)
![image](https://user-images.githubusercontent.com/3512138/31967991-70213e04-b8ee-11e7-8295-9f2a64e88e6b.png)

**System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=iec61850dotnet
  StackTrace:
       at IEC61850.Client.ControlObject.ControlObjectClient_destroy(IntPtr self)
       at IEC61850.Client.ControlObject.Finalize()
  InnerException:** 

**[sample code]**

        public enum Dbpos
        {
            INTERMEDIATE_STATE = 0,
            OFF = 1,
            ON = 2,
            BAD_STATE = 3
        }

        public static void Main(string[] args)
        {
            string hostname = "192.168.0.125";
            int port = 102;

            IedConnection iedConnection = new IedConnection();

            try
            {
                iedConnection.Connect(hostname, port);

                Dbpos stVal = (Dbpos)iedConnection.ReadBitStringValue("IED7SJ63CTRL/Q0CSWI1.Pos.stVal", FunctionalConstraint.ST);
                Validity q = iedConnection.ReadQualityValue("IED7SJ63CTRL/Q0CSWI1.Pos.q", FunctionalConstraint.ST).GetValidity();
                DateTimeOffset t = MmsValue.MsTimeToDateTimeOffset(iedConnection.ReadTimestampValue("IED7SJ63CTRL/Q0CSWI1.Pos.t", FunctionalConstraint.ST).TimeInMilliseconds);

                bool ctlVal = false;

                switch (stVal)
                {
                    case Dbpos.BAD_STATE:
                    case Dbpos.INTERMEDIATE_STATE:
                        break;

                    case Dbpos.OFF:
                        ctlVal = false;
                        break;

                    case Dbpos.ON:
                        ctlVal = true;
                        break;
                }

                ControlObject control = iedConnection.CreateControlObject("IED7SJ63CTRL/Q0CSWI1.Pos");
                control.SetOrigin("192.168.0.100", OrCat.REMOTE_CONTROL);

                switch (control.GetControlModel())
                {
                    case ControlModel.STATUS_ONLY:
                        break;

                    case ControlModel.DIRECT_NORMAL:
                    case ControlModel.DIRECT_ENHANCED:
                        Console.WriteLine(control.Operate(ctlVal) ? "Operated successfully!" : "Operate failed!");
                        break;

                    case ControlModel.SBO_NORMAL:
                    case ControlModel.SBO_ENHANCED:
                        if (control.SelectWithValue(ctlVal))
                        {
                            Console.WriteLine(control.Operate(ctlVal) ? "Operated successfully!" : "Operate failed!");
                        }
                        else
                            Console.WriteLine("Select failed!");
                        break;
                }

                LastApplError error = control.GetLastApplError();

                iedConnection.Abort();
            }
            catch (IedConnectionException ex)
            {
                Console.WriteLine("[IED ERROR: ({0}) {1}] {2}", (int)ex.GetIedClientError(), ex.GetIedClientError(), ex.Message);
            }
            finally
            {
                iedConnection.Dispose();
            }
        }

**Comment by mzillgith** [comment]
The native ControlObject instance contains a reference to the IedConnection. When IedConnection is disposed before the ControlObject this reference is no longer valid. I updated the code and added the IDisposable interface to ControlObject. You should call the ControlObject.Dispose method before the IedConnection.Dispose method.

**Comment by IgorMundstein** [comment]
@mzillgith 

Ok. 

Thx!
