### ISSUE TITLE
MmsConnection_connect can end up in a deadlock for multiple simultaneous connections

### ISSUE THREAD

**Issue by ruccolarobert** [mz-automation/libiec61850#230]
`MmsConnection_connect` will block until `internalConnectionStateChangeHandler` receives a `MMS_CONNECTION_STATE_CLOSED` or `MMS_CONNECTION_STATE_CONNECTED` state. However in some cases (seen when multiple connections are trying to connect simultaneous) the connected/closed state will not show.

Seems to be happening when there is a timeout when waiting for "ACSE initiate response". The nextState is set to `INT_STATE_ERROR` but seems like it should perhaps have been set to `INT_STATE_CLOSE_ON_ERROR`.

The action is taking place in the following part of the code of `iso_client_connection.c`

```
    case INT_STATE_WAIT_FOR_ACSE_RESP:
        {
            uint64_t currentTime = Hal_getTimeInMs();

            if (currentTime > self->nextReadTimeout) {

                if (DEBUG_ISO_CLIENT)
                    printf("Timeout waiting for ACSE initiate response\n");

                self->callback(ISO_IND_ASSOCIATION_FAILED, self->callbackParameter, NULL);

                nextState = INT_STATE_ERROR;  // <--- the issue!?
            }
```

**Comment by mzillgith** [comment]
Seems you are referring to old code. The change you suggested was already done here: 17205ed8742a48f0f3d6915b01eeeed57fcf337e

**Comment by ruccolarobert** [comment]
Yes, it seems like you're right, thought I looked up the latest version of the code, but was actually stuck on 1.4.0 version. Been running 1.4.2.1 for a while and it seems to work better. Will leave this open a little short longer to verify the deadlock issue is resolved

**Comment by ruccolarobert** [comment]
Been running quite stable for a while so I think we can close this one!
