### ISSUE TITLE
ControlObject->mmsConnection == NULL during ControlPerformCheckHandler call

### ISSUE THREAD

**Issue by dimasagalov** [mz-automation/libiec61850#232]
Thus user connection cannot be obtained.
You can easily check this by running client example **iec61850_client_example_control** and server example **server_example_control** 
[server_example_control.c.txt](https://github.com/mz-automation/libiec61850/files/4559722/server_example_control.c.txt)

**Comment by mzillgith** [comment]
This is an internal variable. The right way to get the connection is using the function ControlAction_getClientConnection like here https://github.com/mz-automation/libiec61850/commit/4cb5ffa8c29ec33b7ad43551b190c60eaf193772

**Comment by dimasagalov** [comment]
Yes, I purely understand that I should use  **ControlAction_getClientConnection**. I meant that this function uses **ControlObject->mmsConnection**, which for some reason is NULL...
How can the clientCon be NULL? Anyway, before accepting operate command, I must determine that access by connection is allowed. How can i do this if clientCon == NULL?

**Comment by mzillgith** [comment]
Yes. There is indeed a problem. Sometimes mmsConnection is NULL. It should be fixed now.

**Comment by dimasagalov** [comment]
Thank you, Michael, for a quick fix!
