### ISSUE TITLE
Order of DataAttribute not consistent in iec61850 client

### ISSUE THREAD

**Issue by EtienneBurton** [mz-automation/libiec61850#241]
**Getting DataAttribute tree with:**
   ` dataAttributeList = IedConnection_getDataDirectoryFC(iedConn, &error, nodeRef)`

The order for LPHD1.phyNam is:
```
  hwRev[DC]
  location[DC]
  model[DC]
  name[DC]
  serNum[DC]
  swRev[DC]
  vendor[DC]
```
**Getting DataAttribute values with:**
   ` mmsValP = IedConnection_readObject (iedConn, &error, nodeRef, IEC61850_FC_DC)`
 
The order of the values is:
```
  vendor[DC]
  name[DC]
  hwRev[DC]
  swRev[DC]
  serNum[DC]
  model[DC]
  location[DC]
```
The first list is sorted in alphabetical order. The second list is based on the order of DataAttribute in model.
So the value does not match the name.

**Comment by mzillgith** [comment]
This is caused by the MMS protocol that requires the response of the get-name-list service to be ordered alphabetically. To get the attributes in the same order of the read response you have to use the function _IedConnection_getVariableSpecification_.

**Comment by EtienneBurton** [comment]
Thank you Michael for your quick reply !
I have used the recommended function _IedConnection_getVariableSpecification_ and it works better
