### ISSUE TITLE
CMake and Makefile leak of maintainability

### ISSUE THREAD

**Issue by IniterWorker** [mz-automation/libiec61850#242]
Hello,

I'm currently implementing a Yocto recipe to package your library for embedded purposes. 

It's awful that I need to figure out which header do you haven't register yet in your Makefile because your CMakelist is the mainline updated.

Secondly, besides the awful header files links fact, the current branch 1.4 isn't working with the Makefile.

But, my guts tell me that the current Makefile is used for Linux only and the CMakelist.txt only for Windows or some CPack functionalities. So, cleary that will be an improvement to use [GNUInstallDir](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) in your CMakelist.txt, under Unix architecture.

> I am using eclipse. Setting up a project manually with existing code is quite easy. But I use the IDE only as an editor with powerful code completion and refactoring capabilities. For building/debugging I use make, gdb and other command line tools. Actually I am using cmake only to build the project files for the visual studio tools on windows. 
_- From Michael Zillgith_

I consider that we need to move forward with only one builder support (e.g. CMake). What do you think?

B. r

**Comment by RomainNaour** [comment]
Hello,

Agree that using Makefile build system is not recommended for Yocto recipes or Buildroot packages.
Why not using the CMake infra ?
I also packaged the library for Yocto and Buildroot using CMake without an issue.

Best regards,
Romain

**Comment by IniterWorker** [comment]
@RomainNaour,

I'm not sure about the fact of which is better for the Yocto recipe, both are accepted.

B. r
