### ISSUE TITLE
RCB listener and Network Traffic

### ISSUE THREAD

**Issue by IniterWorker** [mz-automation/libiec61850#243]
Hello,

Maybe do you have some hints for me? It's pretty hard to find advanced information about your implementation and the standard iec61850.

I did some tests with the IEDScout software client to try to figure out that it isn't a big deal. But, I'm looking forward to some hints before going into the production environment.

I'm implementing an MMS with an RCB, and I'm wondering **if the basic polling** example **is enough not to flood my network** when a client listener is connected to my RCB block, mainly if only the ".t" timestamp is the one changing.

I took the time to look into your code, and I observed some particular case handling the value change with different triggers. _My question here is a simple need I to take care of my value change to change the timestamp, or is it already handled by the library?_

Could you point me in the right direction? Thank you for any help you can offer.

Best Regards,

**Comment by mzillgith** [comment]
Hi,
When only the timestamp changes usually no report is triggered.
You have to update the timestamp in your code it is not updated automatically.

**Comment by IniterWorker** [comment]
Hi @mzillgith,

With the present answer, you say that the RCB handles the mechanism to update only on value triggering changes and that I don't need to care about when the update of ".t" will be. Is it correct?

```
while(true)
{
  Lock
  ReadMyState
  Write.q
  Write.t
  Write.sState
  Unlock
  Sleep
}
```

**Comment by mzillgith** [comment]
Yes. That's correct. The order doesn't matter in this case (when lock is applied).

**Comment by IniterWorker** [comment]
Thank you
