### ISSUE TITLE
Add support for permanently enabling RCBs (when RptEna=true & ClientLNs defined in SCL file) for pre-established associations

### ISSUE THREAD

**Issue by andy1547** [mz-automation/libiec61850#251]
I've had a look over the source code and at first glance it seems that the only way for a RCB to be enabled is by the client, just wanted to double check whether this is a hidden feature somewhere.

I'm seeking the ability to pre-enable RCBs on IED Server start, this supports the use-case of permanently used RCBs by known clients (at configuration time RptEna = true & ClientLNs defined in the SCL file).

For BRCBs this would allow updates/changes to be buffered before the client first connects, then sent once association is established.

For both unbuffered & buffered RCBs, this would remove the need for the client to explicitly enable using SetBRCBValues.

**Comment by mzillgith** [comment]
The requested feature is not compatible with the IEC 61850 standard.
