### ISSUE TITLE
i want to read multiple variables at single time ,instead of sending 50 requests  for 50 variables with pyice61850.

### ISSUE THREAD

**Issue by Saleem344** [mz-automation/libiec61850#258]
Hi,
i want to read multiple variables at single time ,instead of sending 50 requests  for 50 variables.
1.
i have found found the some method :
MmsConnection_readMultipleVariables(_self, mmsError, domainId, items)
but i'm getting this error TypeError: in method 'MmsConnection_readMultipleVariables', argument 2 of type 'MmsError *'
In python we have to  pass mmsError type but i'm  not sure what mms error type. If you can help me with this it will be very helpful.
2.
i have tried this method:
    con = iec61850.IedConnection_create()
    conn = iec61850.IedConnection_connect(con,host,tcpPort)
    if(conn==iec61850.IED_ERROR_OK):
        var = "wsDevice/MMXU1.TotVAr"
        vartype = iec61850.IEC61850_FC_MX
        varvalue = iec61850.IedConnection_readObject(con,var,vartype)
        print('value :',str(varvalue))
        if(varvalue!= None):
                value = iec61850.MmsValue_toFloat(item)
                print('item',value)

in output i'm getting this error TypeError: in method 'MmsValue_toFloat', argument 1 of type 'MmsValue const *'

For a long time I've been trying to get the solution for this , but I'm new to python. If you help me with this it will be very helpful.

Thank you

**Comment by mzillgith** [comment]
Hi,
1)
I guess the function _MmsConnection_readMultipleVariables_ would be the right way. The second argument has to be a pointer to the MmsError variable where the function has to store the error code. I don't know if and how this can be done with python.
2)
When you use "wsDevice/MMXU1.TotVAr" as object reference the result will not be a float but a struct. You would need an object reference like ""wsDevice/MMXU1.TotVAr.mag.f" to access only the float attribute.

**Comment by Saleem344** [comment]
> Hi,
> 1)
> I guess the function _MmsConnection_readMultipleVariables_ would be the right way. The second argument has to be a pointer to the MmsError variable where the function has to store the error code. I don't know if and how this can be done with python.
> 2)
> When you use "wsDevice/MMXU1.TotVAr" as object reference the result will not be a float but a struct. You would need an object reference like ""wsDevice/MMXU1.TotVAr.mag.f" to access only the float attribute.

     def test_client():
        con = iec61850.IedConnection_create()
        conn = iec61850.IedConnection_connect(con,host,tcpPort)
        if(conn==iec61850.IED_ERROR_OK):
            var = "wsDevice/MMXU1.TotVAr.mag.f"
            vartype = iec61850.IEC61850_FC_MX
            varvalue = iec61850.IedConnection_readObject(con,var,vartype)
            print('value :',str(varvalue))
            if(varvalue!= None):
                  value = iec61850.MmsValue_toFloat(varvalue)
       else:
            print("connecion error")

still i'm getting output error like this TypeError: in method 'MmsValue_toFloat', argument 1 of type 'MmsValue const *'


there is no function like mmsValue_toStruct  ,IedConnection_readObject how can see the out of this function in readable format???

**Comment by Saleem344** [comment]
In python it is not working perfectly I had to go with C#.
