### ISSUE TITLE
Segfault in mms_goose.c

### ISSUE THREAD

**Issue by PhilipSiEn** [mz-automation/libiec61850#264]
If _GoosePublisher_createEx()_ returns _NULL_ then _GoosePublisher_setTimeAllowedToLive()_ causes a Segfault:

![image](https://user-images.githubusercontent.com/62375879/95594632-7f547b00-0a4b-11eb-871e-b547559b323e.png)

**Comment by mzillgith** [comment]
How can this happen? There is a check for NULL directly after GoosePublisher_createEx. So the code path with GoosePublisher_setTimeAllowedToLive should not be executed.

**Comment by PhilipSiEn** [comment]
Yes, you are right. I think i was working on an older commit when I saw this error. After pulling the latest commit I cannot reproduce it (made the screenshot after the pull).

Sorry for the confusion...
