### ISSUE TITLE
Headers copied into $(INSTALL_PREFIX)/include directory aren't sufficient to use with new project.

### ISSUE THREAD

**Issue by nyx191** [mz-automation/libiec61850#267]
Steps to reproduce on linux system:
clone
// Switch on any branch
make && make install
cd .install/include
echo '#include "iec61850_server.h"
int main(){}' | gcc -x c -

Expected result:
Compilation success
Actual result:
iec61850_server.h:38:10: fatal error: mms_server.h: No such file or directory
   38 | #include "mms_server.h"

**Comment by nyx191** [comment]
Consider adding
LIB_API_HEADER_FILES += src/mms/inc/mms_server.h
in Makefile

**Comment by nyx191** [comment]
Also worth to mention that there is typo in Makefile:
C**G**LAGS += -Wextra
Actually -Wextra wasn't set for a long time ;)
With -Wextra there is dense stream of compiler warnings.

**Comment by mzillgith** [comment]
Should be fixed in the meantime,
