### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by stv0g** [mz-automation/libiec61850#27]
To my understanding, the [linked list implementation](https://github.com/mz-automation/libiec61850/blob/master/src/common/linked_list.c) is not thread safe, which could lead to data races when adding/removing subscribers in the  Sampled Values code.

**Comment by mzillgith** [comment]
Yes you are right. I will add a mutex to protect the subscribers list.

**Comment by stv0g** [comment]
Thanks :)
