### ISSUE TITLE
CDC_CTL_MODEL_SBO_NORMAL

### ISSUE THREAD

**Issue by aignashev** [mz-automation/libiec61850#273]
ControlPerformCheckHandler
for
CDC_CTL_MODEL_SBO_ENHANCED
and
CDC_CTL_MODEL_SBO_NORMAL
differs.

CDC_CTL_MODEL_SBO_ENHANCED works fine - no questions.

CDC_CTL_MODEL_SBO_NORMAL works not right - situations below.

What I do:

1. set for CDC_CTL_MODEL_SBO_NORMAL
ControlPerformCheckHandler by function IedServer_setPerformCheckHandler
and
ControlHandler with fucntion IedServer_setControlHandler

2. Do from client Select with test = true, orCat = station-control

ControlPerformCheckHandler calls with wrong: flag test = false, Control.orCat = 0

from file control.c line 1280

checkResult = controlObject->checkHandler((ControlAction) controlObject,
  controlObject->checkHandlerParameter, NULL, false, false);

3. Do from client Operate с test = true, orCat = station-control
Waiting for callback  ControlHandler
but
wrong callback ControlPerformCheckHandler
it's strange because it callback second time with test = true flag

from file control.c line 1664

checkResult = controlObject->checkHandler((ControlAction) controlObject,
  controlObject->checkHandlerParameter, ctlVal, testCondition, interlockCheck);

**Comment by mzillgith** [comment]
The select operation in SBO_NORMAL mode has no parameters (it is mapped to a single READ of SBO variable in MMS). So these parameters also cannot be provided to the server side callback function.

**Comment by aignashev** [comment]
Hi,

yes we understand. We passed these tests.

Игнашев Антон Владимирович \ Anton Ignashev
Технический Директор \ CTO ООО "ЦентрЭнергоАвтоматика"
Тел.: +74952347643 (доб. 102) Моб.: +79035785000 Сайт : www.cea-energo.ru



ср, 18 нояб. 2020 г. в 20:16, Michael Zillgith <notifications@github.com>:
