### ISSUE TITLE
SVsubscriber latency

### ISSUE THREAD

**Issue by cedricboudinet** [mz-automation/libiec61850#274]
Dear Mickael

I am using svsubscriber to process some SV messages.
I encounter a problem: the SV rate can be 4800Hz or 4000Hz, which leads to a time step smaller that a millisecond.
In the svReceiverLoop, there is a 1ms sleep when no packet has been received.
If a packet arrives during this sleep, it will be taken into account later on.
It implies that if a SV rate is 4000Hz, the subscriber program will handle them by set of four each millisecond instead of handling them every 250us.

I tried to reduce the usleep delay under linux and it works better. But for win32 it seems a bit more complicated. I am right?
Another solution would be to put a timeout to recvfrom using setsockopt and to remove the thread sleep in the receiver loop.

What solution do you think is the best?

Bests
Cedric

**Comment by mzillgith** [comment]
Hi Cedric,
I think the second solution is better.
But maybe using the EthernetHandleSet like it is used in the gooseReceiverLoop.

**Comment by cedricboudinet** [comment]
Thanks for the hint. I will give it a try.
