### ISSUE TITLE
How to compile python binding for Python 3

### ISSUE THREAD

**Issue by PhilipSiEn** [mz-automation/libiec61850#275]
Hi,

by default CMake seems to compile the library for Python 2. I could run the example successfully. With Python 3 I get an Exception.
How can i compile the lib for Python 3?

BTW.: CMake does not add the package to my python installation as described in the manual.

Platform:
Debian 10
Python 2.7.16
Python 3.7.3

**Comment by hanusek** [comment]
```yaml
    - mkdir ./build
    - cd ./build
    - cmake -DBUILD_PYTHON_BINDINGS=ON -DBUILD_PYTHON_VERSION=3 ..
```

**Comment by PhilipSiEn** [comment]
Now I get this error: 
```
CMake Error at /home/z003403h/Qt/Tools/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.16", but
  required is at least "3" (found /usr/bin/python)
```
Is there a parameter for the interpreter too? Or do I have to change the /usr/bin/python symlink to python3?

**Comment by PhilipSiEn** [comment]
It works now. I had to change the python settings in the CMake section of my IDE (Qt Creator).
Thanks!
