### ISSUE TITLE
How to handle select-before-execute in a server?

### ISSUE THREAD

**Issue by gboor** [mz-automation/libiec61850#278]
As the title says; I'm just wondering if there is some sort of default stub for this that handles timeout etc., or if this is something that needs to be created from scratch.

I'm using the C# lib. If anyone has some examples of how to do this, that would be helpful too!

**Comment by mzillgith** [comment]
You don't have to handle it. The library is doing that for you by default .

**Comment by gboor** [comment]
That is good to hear!

But how do I mark an address as select-and-execute instead of direct execute? And how do I set the timeout? The party we are integrating with has some specific requirements for this... like returning errors if we try an execute before issuing a select, or returning errors if there is too much time between the select and execute.

**Comment by gboor** [comment]
I just realized that this may not be the right repo... I am using the lib60870.NET, which has its own repo.

I will close this and move my question there. Apologies!
