### ISSUE TITLE
Unnecessary delay in SVReceiver

### ISSUE THREAD

**Issue by stv0g** [mz-automation/libiec61850#28]
The SVReceive loop uses `Thread_sleep()` to wait 1 millisecond in case no packet is currently in the input buffer. This time is lost and can increase the worst case latency to receive a SV packet to 1 ms.

This is mainly because `Ethernet_receivePacket()` does not block and immediately returns using the `MSG_DONTWAIT` flag.

I propose to add a `poll()` / `select()` compatible interface.

**Comment by stv0g** [comment]
I noticed that the _TCP_ socket HAL uses a HandleSet to implement a portable `select()`.

Should we try to extend this HandleSet to support _Ethernet_ sockets as well?

**Comment by mzillgith** [comment]
I am not sure if a select style mechanism works well on most platforms. E.g. the windows port that uses winpcap I think it doesn't support select. Adding a timeout parameter to Ethernet_receivePacket might be a solution  Inside the function select or some other platform specific mechanism could be used. But when using multiple ethernet interfaces that might not work.

**Comment by stv0g** [comment]
I think there are two ways to fix this issue:

## Properly extend `HandleSet` to support Ethernet sockets

Pcap provides `pcap_get_selectable_fd()` which could be used on Linux / BSD.
However, it is not provided by WinPcap.
Instead, `pcap_getevent()` must be used to get an event handle which can be used for asynchronous IO.

My first Idea was to extend the Socket HAL's HandleSet with a function `HandleSet_addEthernetSocket()`.
This way, the HandleSet could be used for all sorts of asynchronous IO (Socket, Pcap, Filesystem).

## Add a timeout / blocking mode to the Ethernet HAL

Alternatively, we could just add a function `Ethernet_setBlocking()` or add an timeout as you suggested.

Which approach do you prefer?

**Comment by mzillgith** [comment]
Hi, I am still not sure what is the best solution.
The blocking Ethernet will not be very useful when using more than one interface. 
So maybe a special "HandleSet" only for the Ethernet API could be a solution. It should be used in such a way that the implementation can be skipped if select style I/O is difficult to implement for a platform, e.g. that the receive function can be called in a interrupt service routine. I am doing this with the Socket API as well. It is not required to implement but it may  improve CPU usage and response time on platforms that support it.

**Comment by stv0g** [comment]
Okay, I agree. I will prepare a pull request for an `EthernetHandleSet`.

We mainly use Linux, So I can't really test BSD or Windows.

**Comment by stv0g** [comment]
This issue is now solved by select() / poll() semantics in EthernetHandleSet()
