### ISSUE TITLE
Please, add Handler (like ControlPerformCheckHandler and ControlHandler) for Cancel request

### ISSUE THREAD

**Issue by stasm78** [mz-automation/libiec61850#280]
Please, add Handler (like ControlPerformCheckHandler and ControlHandler) for Cancel request in SBO control models.
We want to do some action in own program, when Select was Canceled (something like switch off LED)

Thank you!

**Comment by mzillgith** [comment]
There is now a new callback (ControlSelectStateChangedHandler) that can be called whenever the select state of a control object changes.

**Comment by mzillgith** [comment]
I guess this can be closed now.

**Comment by stasm78** [comment]
Yes! Thank You very much!
