### ISSUE TITLE
Parse empty string to RCB "RptID"

### ISSUE THREAD

**Issue by str52** [mz-automation/libiec61850#284]
According to IEC61850-8-1 ed.2 subclause 17.2.1 (about "RptID"):

"If the control block RptID value is NULL, then the MMS data shall contain the object reference 
specifying the control block which caused the report to be generated."

I can`t write empty string to RCB "RptID", libiec changes it to default value. This thing is also a part of UCA conformance tests for ed2 server (sRp4 and sBr4). According to IEC61850 ed2 server should accept empty string to RCB setting "RptID", but in MMS report should be default "RptID" value.

**Comment by mzillgith** [comment]
In our test cases this works. "RptID" is not changed when writing empty string. I tested with v1.5 branch but in v1.4 it should be the same.

**Comment by mzillgith** [comment]
Was fixed here:  041325ef69a54d39ddbf94a968d6d1f3e6efbe7a
