### ISSUE TITLE
Dead Lock happens when FileRead timeout in client side

### ISSUE THREAD

**Issue by Tachiguishi** [mz-automation/libiec61850#285]
When `FileRead` timeout, client will send a `FileClose` to server.

But in fact, client can't send out the `FileClose` because it will block at `addToOutstandingCalls` in function `sendAsyncRequest`.

`addToOutstandingCalls` wants to lock the `MmsConnection.outstandingCallsLock` which is already locked by `mmsIsoCallback`.

So, a `dead lock` happen and the receive thread and send thread block forever.

**Comment by mzillgith** [comment]
Thanks for the hint. Should be fixed now.
