### ISSUE TITLE
Functional constraint BL

### ISSUE THREAD

**Issue by Berendej** [mz-automation/libiec61850#287]
Regarding Data Attribute 'blkEna'. Though the support of blkEna is included in library, nevertheless handling functional constraint BL is not provided.
E.g. : functions 
getFunctionalConstraintForWritableNode() 
IedServer_setWriteAccessPolicy() 
getAccessPolicyForFC() 
provide handling of "CF", "DC", "SP", "SV", "SE" but not "BL". 
Therefore server always responses with 'access denied' when client tries to write into 'blkEna'.

**Comment by mzillgith** [comment]
Thanks for the hint!
It should be fixed now.
