### ISSUE TITLE
activeSgChangedHandler: crash while try ClientConnection_getSecurityToken(connection)

### ISSUE THREAD

**Issue by stasm78** [mz-automation/libiec61850#289]
In callback activeSgChangedHandler (maybe and in other, where present parameter 'ClientConnection connection') try to get security token by function 'ClientConnection_getSecurityToken(connection)'. Application crashes.
Try this and on Your example 'server_example_setting_groups' simple by add code:
static bool
activeSgChangedHandler (void* parameter, SettingGroupControlBlock* sgcb,
        uint8_t newActSg, ClientConnection connection)
{
    printf("Switch to setting group %i\n", (int) newActSg);
//---added string
    int* pi = ClientConnection_getSecurityToken(connection);

    loadActiveSgValues(newActSg);
    return true;
}

Crashed too.

Or I was doing something wrong.

Screen of gdb backtrace:
screen of core[https://drive.google.com/file/d/1ExBPbIWPJBJef9OWm_uM-iIJd4wsdbW-/view?usp=sharing](url)

**Comment by stasm78** [comment]
https://drive.google.com/file/d/1ExBPbIWPJBJef9OWm_uM-iIJd4wsdbW-/view?usp=sharing

**Comment by mzillgith** [comment]
Thanks for the hint. Seems there was the wrong object provided in the callback. It should be fixed now.

**Comment by stasm78** [comment]
Problem was fixed!
Thank You!
I think, issue can be closed
