### ISSUE TITLE
ReportControl and rptID is empty

### ISSUE THREAD

**Issue by Uskok** [mz-automation/libiec61850#3]
Hi Michael,

I made some testing together with Anvil from Triangle MicroWorks (IEC61850 Test Suite). There is one case file TMWSample.icd where prtID is not set inside ReportControl.
You can register as client the reports but the callback function is not executed.

I found small problem in private_IedConnection_handleReport(IedConnection self, MmsValue* value)
(file client_report.c)

----
    while (element != NULL) {
        ClientReport report = (ClientReport) element->data;
        char repID[129];
        char* rptId = report->rptId;

        if (rptId == NULL || (rptId && (strlen(rptId)== 0)))
        {
            strcpy(repID, report->rcbReference);
            StringUtils_replace(repID, '.', '$');
            rptId = repID;
        }

        if (strcmp(MmsValue_toString(rptIdValue), rptId) == 0) {
            matchingReport = report;
            break;
        }

        element = LinkedList_getNext(element);
    }
----

More or less rptId pointer was not NULL but the string was empty.
Regards,

    Boris

**Comment by mzillgith** [comment]
Hi Boris,
thanks. I will commit the fix.
Regards,
Michael

**Comment by Uskok** [comment]
Hi Michael,
Thanks for the fast replay. You can close the case.
Regards,

    Boris
