### ISSUE TITLE
Compile Error on Window 10 (64bit) - Branch 1.5

### ISSUE THREAD

**Issue by Namgung-Dongwoo** [mz-automation/libiec61850#301]
Hi There, 

An error occurs in the UDP socket added in 1.5
I think, the implementation is not complete. 
Please check it.

**Comment by mzillgith** [comment]
Hi. Yes this branch is still under development and not everything ready. But I don't know why it shouldn't compile. I tried compiling with Visual Studio and had no problem.

**Comment by Namgung-Dongwoo** [comment]
I compiled in the mingw environment, 
And the reason because the function declaration in the header and the function declaration in the implementation are different.

hal_socket.h
UdpSocket_receiveFrom(UdpSocket self, char* address, int maxAddrSize, uint8_t* msg, int msgSize);

socket_win32.c
UdpSocket_receiveFrom(UdpSocket self, char** address, int maxAddrSize, uint8_t* msg, int msgSize)

"char* address" and "char** address"

**Comment by mzillgith** [comment]
I see. It should compile now.
