### ISSUE TITLE
File services: GetFileAttributeValues service (IEC 61850-7-2-2010: paragraph 23.2.4)

### ISSUE THREAD

**Issue by stasm78** [mz-automation/libiec61850#305]
Good day!
Are You planning the implementation of this service?

Thank You in advance for Your response.

**Comment by mzillgith** [comment]
You can get the file attributes with the function _IedConnection_getFileDirectory_

**Comment by stasm78** [comment]
From Your documentation (https://libiec61850.com/libiec61850/documentation/library-features/):

S60 | GetFileAttributeValues | TP | Y | Y | since version 0.7.1

What about this information?
Is this error in documentation, or I something don't understand?

**Comment by mzillgith** [comment]
The _IedConnection_getFileDirectory_ function is for the client side implementation of the GetFileAttributeValues service.

**Comment by stasm78** [comment]
[SOLVED]
Thank You for answer!
Now all is clear for me!

**Comment by stasm78** [comment]
[SOLVED]
Thank You for answer!
Now all is clear for me!
