### ISSUE TITLE
Clock synchronized for IEC-61850 server

### ISSUE THREAD

**Issue by peter279k** [mz-automation/libiec61850#311]
As title, it seems that the common IEC-61850 library provides `Timestamp_setClockNotSynchronized` to determine whether the clock is not synchronized.

But there are all examples that use the `Timestamp_setClockNotSynchronized` to set `true` and let them clock not synchronized.

Is there any example about how to use above function to present the clock synchronized example?

Thanks.

**Comment by mzillgith** [comment]
Hi,
When the clock is synchronized just don't set the flag (don't call the function).
If the flag is already set you can call code like  `Timestamp_setClockNotSynchronized(&iecTimestamp, false);`

**Comment by peter279k** [comment]
Ok. Thanks.
