### ISSUE TITLE
examples: goose_publisher and goose_subscriber

### ISSUE THREAD

**Issue by kenhutaiwan** [mz-automation/libiec61850#313]
Dear All:

I'm on my way to study GOOSE, after compiling and running examples: goose_publisher and goose_subscriber, I find that the subscriber does not receive any GOOSE messages.
Does anyone run into this problem too? How do I resolve this ?
Right now I am using libiec61850 branch v1.4

Thanks in advance.

**Comment by kenhutaiwan** [comment]
Sorry , I find that if I use lo(loopback) interface for both publisher and subscriber, goose messages will be received.

**Comment by MinhQuanddt** [comment]
Hello, i get some problem with goose subscriber, can u support me

**Comment by zengyilida111** [comment]
> Sorry , I find that if I use lo(loopback) interface for both publisher and subscriber, goose messages will be received.

i run into the same problem like you, goose messages will not be received except using lo(loopback).weird situation。。。confusing

 even i run publisher and subscriber example at separate two real linux machine.
