### ISSUE TITLE
SVPublisher_ASDU_SetSmpRate not working as expected!

### ISSUE THREAD

**Issue by Qirtas** [mz-automation/libiec61850#315]
I am generating a fixed sample rate SG traffic in pub/sub mechanism using the below statements but for some unknown reason, I'm getting random sample count after execution at both publisher and subscriber end. 

`SVPublisher_ASDU_setSmpMod 	(asdu1, IEC61850_SV_SMPMOD_SAMPLES_PER_SECOND);
  SVPublisher_ASDU_setSmpRate 	(asdu1, 1000);`

Any leads would be really appreciated.

**Comment by mzillgith** [comment]
This question is already answered here #308
