### ISSUE TITLE
No reference to ConnectionEventHandler (C#)

### ISSUE THREAD

**Issue by basilfx** [mz-automation/libiec61850#321]
[This](https://github.com/mz-automation/libiec61850/blob/fcefc746fea286aeaa40d2f62240216da81c85e5/dotnet/IEC61850forCSharp/IEC61850ClientAPI.cs#L1791) line states that I should use `ConnectionEventHandler` instead of `InstallConnectionClosedHandler`, but I cannot find any reference to this `ConnectionEventHandler` in the source.

I presume this line is incorrect, so my question is: what should I use instead?

**Comment by mzillgith** [comment]
You are right. The line is incorrect. It should be `StateChangedHandler`

**Comment by FindPath** [comment]
Hello, I'm C# developer, too
