### ISSUE TITLE
Forget to release outstanding call in function deleteFileAndSetFileHandler?

### ISSUE THREAD

**Issue by Tachiguishi** [mz-automation/libiec61850#322]
There is no code to release outstanding call in function
`deleteFileAndSetFileHandler (uint32_t invokeId, void* parameter, MmsError mmsError, bool success)`
in file `src/iec61850/client/ied_connection.c`.

I think there should be.

Do you forget it or do I misunderstand the logic here?

**Comment by mzillgith** [comment]
You are right. It should be there. Thanks for the hint!
