### ISSUE TITLE
Cannot compile v1.5 without GOOSE support

### ISSUE THREAD

**Issue by pavel-ch** [mz-automation/libiec61850#325]
Trying to compile v1.5 (Windows 10 VS2015 32-bit), without GOOSE:
In mms_mapping.c, I get an error:
![image](https://user-images.githubusercontent.com/771816/116537310-59f36580-a8e6-11eb-851a-d72e1ed6e05e.png)

Apparently, there is missing the conditional define instruction:
![image](https://user-images.githubusercontent.com/771816/116537397-768f9d80-a8e6-11eb-9776-cc4a312f0430.png)

After that, the compilation is successful.

**Comment by mzillgith** [comment]
Thanks for the hint! Should be fixed now.
