### ISSUE TITLE
v1.5 server_example_control - SBO structure not present

### ISSUE THREAD

**Issue by pavel-ch** [mz-automation/libiec61850#326]
In this example, the control variables in simpleIOGenericIO/GGIO1.SPCSO2 for example, with ctlModel set to 2 (sbo-with-normal-security), there shall be the SBO structure defined with the same members like in the Oper structure.
Instead, after **reading the model from server**, I see the following (SBO as visible_string, not a structure):
![image](https://user-images.githubusercontent.com/771816/116539604-531a2200-a8e9-11eb-947a-2bba440f31f9.png)

For variables with ctlModel = 4 (sbo-with-enhanced-security, SPCSO4 and SPCSO8) this works well, seeing the SBOw structure correctly.
This was verified in two independent client tools.

On the contrary, the libiec6850 client_example_control works well, probably does not depend on reading the server model (SBO struct) completely.

**Comment by mzillgith** [comment]
Hi,
According to the standard SBO (different from SBOw) is a visible string and select has to be done by reading it (see IEC 61850-8-1:2011 20.5.1 or in the corresponding ed. 2.1 document).
Here the IEDExplorer is not implemented correctly.

**Comment by pavel-ch** [comment]
Thank you, I will look into the standard. Do you have a reference, so that I do not need to search for that? - no issue if not. Thanks.

**Comment by mzillgith** [comment]
It's here:
IEC 61850-8-1:2011 section 20.5.1 should be page 100.

**Comment by pavel-ch** [comment]
Thank you, my bad, I overlooked your navigation before...😀

**Comment by pavel-ch** [comment]
Right, correct. Closing the issue, sorry for misunderstanding.
