### ISSUE TITLE
BIOCIMMEDIATE - Enable "immediate mode"

### ISSUE THREAD

**Issue by IVbI4** [mz-automation/libiec61850#328]
https://github.com/mz-automation/libiec61850/blob/1bb76893a225f37df8b4732b37c1271bb517cb44/hal/ethernet/bsd/ethernet_bsd.c#L316

To enable "immediate mode" you need to change: 
``` 
/* Activate immediate mode. */
optval = 1;
if (ioctl(self->bpf, BIOCIMMEDIATE, &optval) == -1)
```

I had a problem receiving GOOSE-messages without this fix.

**Comment by mzillgith** [comment]
Thanks for the hint. It's fixed now.
