### ISSUE TITLE
ControlPerformCheckHandler function interface, added parameter ControlAction, removed ClientConnection.

### ISSUE THREAD

**Issue by Berendej** [mz-automation/libiec61850#333]
Version 1.4.2 defines ControlPerformCheckHandler as:
typedef CheckHandlerResult (*ControlPerformCheckHandler) (ControlAction action, void* parameter, MmsValue* ctlVal, bool test, bool interlockCheck);
previously it was defined as:
typedef CheckHandlerResult (*ControlPerformCheckHandler) (void* parameter, MmsValue* ctlVal, bool test, bool interlockCheck,
        ClientConnection connection);

ControlAction=void*

When callback controlObject->checkHandler() is calling parameter "action" mostly has type ControlObject, but once it has type MmsMapping.
So the application which uses library can't use parameter "action" because it's type is undefined.
No one example utilize parameter "action".

On the other hand parameter "ClientConnection connection" was removed.
But it is used to authenticate client. 
Example server_example_password_auth uses this parameter even in version 1.4.2.
In fact server_example_password_auth uses previous ControlPerformCheckHandler interface.
Needless to say it doesn't work.

My proposal is: define first parameter of ControlPerformCheckHandler callback 
as a pointer to a strictly defined structure. Such as:
{
    ClientConnection connection;
    ... // <- here other members follow. The ones "ControlAction action" parameter was intended for.
    ... // <- the purpose of this members is not clear for me but still there is
        // <- a possibility to add as many as one likes
}    
instead of "void *action"

**Comment by mzillgith** [comment]
It is intended that you use the functions starting with "ControlAction_" to use the _action_ parameter. E.g. the function _ControlAction_getClientConnection_.

The use of MmsMapping in one case is a bug and should be fixed now.

**Comment by Berendej** [comment]
Thank you.
