### ISSUE TITLE
Harmonisation of Sampled Values subscriber / publisher

### ISSUE THREAD

**Issue by stv0g** [mz-automation/libiec61850#34]
Hi,

I noticed that the API of Sampled Values subscriber and publisher both use ASDU's as their central entity for storing exchanged measurements.

Both APIs have their own implementations of this data structure: `SVClientASDU` vs `SV_ASDU`.

I also noticed that the publisher uses a different naming scheme than the subscriber: `SampledValuesPublisher` vs `SVSubscriber`.

I would volunteer to clean up the API by:
- renaming the publisher code to use the `SV` prefix
- Combine the two implementations of Sampled Values ASDUs into one

I would like to know what other users of the library think about these changes and whether they might be merged?

Renaming the functions will break ABI compatibility.

**Comment by mzillgith** [comment]
Hi Steffen,
I agree that the naming is not very consistent. Also for the different ASDU data structures names like SVSubscriberASDU and SVPublisherASDU would be more clear.
Regarding the two ASDU data structures: As they have different purposes (one for encoding, the other for decoding) I don't know if it us useful to unify them.
Also regarding renaming I don't like it very much as it will break existing applications. In general I try to prevent any API changes that will break existing application, and avoid if not required to implement important features.

**Comment by stv0g** [comment]
My work has been merged into the develop branch. Thanks Michael.
