### ISSUE TITLE
IedConnection_getDataDirectory retreiving correct DAs order

### ISSUE THREAD

**Issue by Morand84** [mz-automation/libiec61850#344]
Hi,

I'm trying to cache DA nodes from Datasets using getDataDirectory functions:
LinkedList dataAttributes = IedConnection_getDataDirectory(con, &error, doRef);

Unfortunately in some cases for some reasons DA order is not as reported in ICD, IedScout and Wireshark.

For Example I'm getting this DO listing from library IedConnection_getDataDirectory:

  LN: L21PTRC1
......
    DO: Op
      DA: general
      DA: phsA
      DA: phsB
      DA: phsC
      DA: q
      DA: t

While in CID, IedScout (and from wireshark order) I got:
![image](https://user-images.githubusercontent.com/35305126/127858647-38939332-9011-4e35-8f03-bed6ff8cd712.png)

So the CID defined proper order would be:

  LN: L21PTRC1
......
    DO: Op
      DA: general
      DA: q
      DA: t
      DA: phsA
      DA: phsB
      DA: phsC

Is there a method to retreive from client discovery these DA informations correctly sorted as defined in CID?

A correctly sorted answer would be very useful for parsing reporting / goose blocks just performing a preliminary recoursive discovery of DO/DA.

Thanks a lot,
Francesco Morandi

**Comment by mzillgith** [comment]
Hi,
IedConnection_getDataDirectory (and other library functions) is using the getNameList service. This service returns the names in alphabetic order not in the order defined in the CID file. The function returns the names in the order it receives from the device.

The is another function you can use to get the attributes in the correct order: IedConnection_getVariableSpecification. It returns all data attributes of a specifc FC and also the type information.

Regards

**Comment by Morand84** [comment]
IedConnection_getVariableSpecification (instead of IedConnection_getDataDirectory) works like a charm for retreiving correct elements in correct order.
Thanks a lot.
BR

**Comment by chenjing1294** [comment]
@mzillgith Hello, how can I get all the properties under the data object in the correct order? Because the data object has no FC, the following call reports an error.
```C#
MmsVariableSpecification specification = con.GetVariableSpecification("SampleIEDDevice1/DGEN1.Mod", FunctionalConstraint.ALL);
foreach (MmsVariableSpecification elementSpec in specification)
{
    Console.WriteLine("           " + elementSpec.GetName() + " : " + elementSpec.GetType());
}
```

IED_ERROR_OBJECT_REFERENCE_INVALID
