### ISSUE TITLE
Error occuring during TLS connection establishment

### ISSUE THREAD

**Issue by rakeshg83** [mz-automation/libiec61850#349]
We had occurred following error during the execution of client server example programs tls_server_example and tls_client_example.
During handshaking process till CASE " MBEDTLS_SSL_CLIENT_CHANGE_CIPHER_SPEC " it worked as expected.
But In CASE  "MBEDTLS_SSL_CLIENT_FINISHED" the return value should be zero.
But we got  in function  **mbedtls_ssl_safer_memcmp**

mac_peer==41155316 
mac_expect==41155356
diff=255 (this value has to be 0 for connection establishment)
But we are getting 255 constantly in all runnings.

Kindly help us to resolve the issue. Thanks in advance

**Comment by mzillgith** [comment]
I cannot reproduce this issue.
