### ISSUE TITLE
Question: Info on PLC connection

### ISSUE THREAD

**Issue by pedro-ricardo** [mz-automation/libiec61850#351]
Hello, thanks for the library.
We successfully used this library with the server/client examples available, but we are having some trouble with the connection with a PLC that uses MMS protocol.

We are currently trying to connect with a PLC from **ABB** model `AC 800M`.

Their manual separates MMS and IEC61850. Ans says that MMS exists by default for communication although to use a IEC61850 protocol an extra part is needed.

So I have a couple of questions.
1. Do you guys have any experience in connecting with this PLC brand ?
2. Are MMS and IEC61850 different things?

**Comment by mzillgith** [comment]
I have no experience with the mentioned PLC brand but I know that it cannot be used out of the box with libiec61850

IEC 61850 uses a subset of MMS. The ABB PLC might use a different subset of MMS.

**Comment by pedro-ricardo** [comment]
Thanks,
we saw that the library can't even shake hands with it .. it fails on connect.

Must be a different MMS implementation.
