### ISSUE TITLE
Doubt in mbedtls version support

### ISSUE THREAD

**Issue by lekshmigvarrier** [mz-automation/libiec61850#352]
When we are using the version mbedtls-2.16.6 with libiec61850-1.5, the TLS connection is established successfully. But when we use the 2.7.19, the connection fails(we renamed 2.7.19 and 2.16.6 versions as 2.16 and put in the folder third_party\mbedtls\mbedtls-2.16 ). 
We had occurred following error during the execution of client server example programs tls_server_example and tls_client_example using 2.7.19 version.
During handshaking process till CASE " MBEDTLS_SSL_CLIENT_CHANGE_CIPHER_SPEC " it worked as expected.
But In CASE "MBEDTLS_SSL_CLIENT_FINISHED" the return value should be zero.
But we got in function mbedtls_ssl_safer_memcmp

mac_peer==41155316
mac_expect==41155356
diff=255 (this value has to be 0 for connection establishment)
But we are getting 255 constantly in all runnings.

Kindly help us to resolve the issue. Thanks in advance. 
Please let us know the supporting versions of mbedtls.

**Comment by mzillgith** [comment]
The current version of the library is designed to work with mbedtls 2.16. So you should only use this version of mbedtls.
