### ISSUE TITLE
IedConnection_getDataSetDirectory asyn function or alternative method?

### ISSUE THREAD

**Issue by user0363** [mz-automation/libiec61850#359]
Hi everyone,
I'm trying to run IEC 61850 client application for my project. I'm using single threaded async functions. For now everything works great. I managed to connect to IEC 61850 server, send operate command and subscribe to unbuffered report control block.  

I know that there is options to include data reference inside every report but I would like to avoid sending unnecessary data. 
Is there any replacement for IedConnection_getDataSetDirectory function for use in single threaded asyn mode? I would like to get list of data objecte names inside dataset with correct order.

**Comment by mzillgith** [comment]
Hi,
You can use the function MmsConnection_readNamedVariableListDirectoryAsync.

**Comment by user0363** [comment]
Thank you for your response. Managed to get list of dataset variables
