### ISSUE TITLE
Missing CONFIG_INCLUDE_GOOSE_SUPPORT directive in the MmsMapping_useIntegratedGoosePublisher method

### ISSUE THREAD

**Issue by Sedighzade** [mz-automation/libiec61850#361]
In version 1.5, in the **mms_mapping.c** file, **MmsMapping_useIntegratedGoosePublisher** method should be changed to this:
`MmsMapping_useIntegratedGoosePublisher(MmsMapping* self, bool enable)
{
#if (CONFIG_INCLUDE_GOOSE_SUPPORT == 1)
    self->useIntegratedPublisher = enable;
#endif    
}`

**Comment by mzillgith** [comment]
It's already like this. Or did I miss something?

**Comment by Sedighzade** [comment]
Sorry for late response. I rechecked from .tar file I had downloaded a few months ago and it has the problem. I downloaded current .zip file from this repo and it has no problem, so If you agree, we can close this.

**Comment by ironcrowntaoist** [comment]
这是来自QQ邮箱的自动回复邮件。
 
谢谢,您的邮件已收到,我会第一时间给您回复的,麻烦了.
