### ISSUE TITLE
How to implement MMS with TLS 1.2.?

### ISSUE THREAD

**Issue by killReal99** [mz-automation/libiec61850#372]
Good afternoon, I'm trying to implement TLS 1.2. for MMS using the library libiec61850. When a connection is established, the interaction is interrupted at the stage "Client Key Exchange".
Also, when monitoring the interaction through wireshark, I see that an error is displayed at the "Certificate Request" stage. I use default certificates, the project is built through CMake on Windows and TLS 1.1. works flawlessly. In the file tls_mbedtls.c I changed only the values of the minimum and maximum versions to TLS 1.2.
Thank you in advance for your response.
![image](https://user-images.githubusercontent.com/85346432/155838000-1ec0c8de-f0e4-43c8-b9b1-fa742508c54f.png)
![image](https://user-images.githubusercontent.com/85346432/155838005-d91ba2b6-039f-4b43-acb3-78cb6ad5e237.png)

**Comment by epasinetti** [comment]
Excuse me, have you solved this issue ? I'm facing a similar problem
