### ISSUE TITLE
IEC 61850 server: MMS_SERVER invalid protocol version when protocolVersion = 2 

### ISSUE THREAD

**Issue by DonavanMartin** [mz-automation/libiec61850#379]
Hi,

We have a client using SIEMENS IEC Browser. 
This software use MMS protocolVersion = 2 which it's not implemented in this library... 

Best regards

<img width="930" alt="Capture d’écran, le 2022-03-27 à 11 25 34" src="https://user-images.githubusercontent.com/7544240/160288662-9412dded-2f32-421a-aa3f-fc9ce18116d5.png">

**Comment by mzillgith** [comment]
Hi,
Thank you for your bug report. Only version number < 1 is invalid. The latest MMS (minor) version number is 4. 2 is an older version number.

**Comment by DonavanMartin** [comment]
The code is showing that invalid version is any version not equal to 1...

```
if (protocolversion != 1)
    if (DEBUG MMS SERVER)
        printf("MMS SERVER: invalid protocol version su\n", protocolversion);
```
