### ISSUE TITLE
Malformed SV packet with SVID over 127 bytes

### ISSUE THREAD

**Issue by jlipponen** [mz-automation/libiec61850#382]
Hi!

I noticed that using an SVID over 127 bytes results in a malformed SV packet:
![malformed-sv-packet](https://user-images.githubusercontent.com/51286274/162692711-ef5887fd-3c5a-44d1-aa99-ba4b6ac1a466.JPG)

I think this happens because [SVPublisher_ASDU_getEncodedSize()](https://github.com/mz-automation/libiec61850/blob/210cf30897631fe2006ac50483caf8fd616622a2/src/sampled_values/sv_publisher.c#L323) hard codes the "header" of the _svID_ field of an ASDU to 2 bytes (_0x80_ + _L_). However, according to the standard, _L_ may be multiple bytes in length. On the encoding side, this varying length is handled by the [BerEncoder_encodeLength()](https://github.com/mz-automation/libiec61850/blob/fcefc746fea286aeaa40d2f62240216da81c85e5/src/mms/asn1/ber_encoder.c#L28) function.

**Fix proposal**
Implement a _BerEncoder_getEncodedLength()_ function to _ber_encoder.c_ and use it in _SVPublisher_ASDU_getEncodedSize()_ instead of a hard coded magic value **2**.

**Comment by mzillgith** [comment]
Hi.
Thank you for your bug report!
It should be fixed now

**Comment by jlipponen** [comment]
Well that was fast! Thank you! :)
