### ISSUE TITLE
Enabling & testing TLS

### ISSUE THREAD

**Issue by tomaskul** [mz-automation/libiec61850#384]
Hi

I'm trying to enable `IedServer` to publish data over TLS connection. But I'm unable to see any TLS packets using wireshark. I've tried running the `tls_server_example` and `tls_client_example` projects within dotnet.sln (both individually and side-by-side) & while the projects run, I didn't see any TLS packets.

My questions being:
- How do I prove that `IedServer` is publishing data over TLS?
- What port is used to publish data/how do I specify the port?

Library configuration:
- libiec61850 version: 1.5.1
- mbedtls version: 2.16.12
- C# wrapper
- build generated using: `cmake .. -WITH_MBEDTLS=1`
- built for: Visual Studio 17 2022
- C compiler identification: MSVC 19.31.31106.2
- CXX compiler identification: MSVC 19.31.31106.2

My understanding of this standard is fairly limited, so please let me know if I've overlooked something.

Thank you for your work on this library!
Kind regards,
Tomas

**Comment by mzillgith** [comment]
Hi,
Looking at the console output of the client you should see if the connection is established and data can be received.
The default port for MMS over TLS is 3782. When using wireshark you probably have to tell wireshark that packets for port 3782 are TLS traffic (in the menu use "Analyze" -> "Decode As ...".

**Comment by tomaskul** [comment]
Hi Michael,
Thank you, your answer has helped. Final question since I haven't found clarification in code or docs;

What functionality are the `AllowOnlyKnownCertificates` flag and `.AddAllowedCertificate(...)` function calls supposed to facilitate?

To try & understand I configured `IedServer` like this:
```cs
TLSConfiguration result = new TLSConfiguration
{
   ChainValidation = true,
   AllowOnlyKnownCertificates = true
};
result.SetCACertificate(new X509Certificate2("root.cer"));
result.SetOwnCertificate(new X509Certificate2("server.cer"));
result.AddAllowedCertificate(new X509Certificate2("server.cer"));
result.SetOwnKey("server-key.pem", null);
```
and when I connect using same approach as used in `tls_client_example` c# example, I get "Access Denied (49)" TLS error, whereas having `AllowOnlyKnownCertificates = false` and not using `.AddAllowedCertificate(...)` on the server leads to successful handshake.

**Comment by mzillgith** [comment]
When setting AllowOnlyKnownCertificates only peers with known certificates are allowed to connect, all other certificates are rejected. And the allowed ("known") certificates have to be set with the AddAllowedCertificate method.
Using this features it is possible to control exactly who can connect.

**Comment by tomaskul** [comment]
Thank you for the clarification Michael!
