### ISSUE TITLE
IEC 61850 server: MMS_SERVER invalid protocol version when protocolVersion = 2

### ISSUE THREAD

**Issue by DonavanMartin** [mz-automation/libiec61850#390]
Protocol failed when MMS_SERVER protocolVersion = 2.

see issue: #379

```
if (protocolversion != 1)
    if (DEBUG MMS SERVER)
        printf("MMS SERVER: invalid protocol version su\n", protocolversion);
```

**Comment by mzillgith** [comment]
You are referring to an older version. This has already been fixed here https://github.com/mz-automation/libiec61850/commit/5fe49d4618cfbb092e7abea6b26f13e0a91219a1
