### ISSUE TITLE
MmsVariableSpecification_getName

### ISSUE THREAD

**Issue by Uskok** [mz-automation/libiec61850#4]
Hi Michael,

I am not able to get name from MmsVariableSpecification. It is always empty and I cannot find the code in the library where the name is assigned.

```
MmsVariableSpecification* var = IedConnection_getVariableSpecification(con, &error, dataAttributeReference, fc);
if(error != IED_ERROR_OK)
{
    printf("Failed to read Variable Specification (error code: %i)\n", error);
    return;
}
printf("Variable Name: %s\n", MmsVariableSpecification_getName(var));
```
Best Regards,
    Boris

**Comment by mzillgith** [comment]
Hi Boris,
the underlying MMS service doesn't send the name of the variable requested. This is not required because you already know the name (you need it when you send the request). The service does only provide the component names in case the variable is a structure (MMS_STRUCTURE). 
Regards,

**Comment by Uskok** [comment]
Hi Michael,

This is not logic for me.
if I start with 
 ` MmsVariableSpecification* var = IedConnection_getVariableSpecification(con, &error, dataAttributeReference, fc);`

as the top variable specification and collect all nested children, I would expect to see the names.
I can start from "simpleIOGenericIO/GGIO1.AnIn1" and with the navigation over MmsVariableSpecification I would like to analyze what is behind.
In this case:

- mag
-- f
- q
- t

I have defined FCDA in DataSet but for the size, the names and order of the names I must ask server.
The order of nested MmsVariableSpecification elements is the same what I will receive in the reports or 
with IedConnection_readObject.

Regards,

**Comment by mzillgith** [comment]
Hi Boris,
If you investigate the MmsVariableSpecification structure you should be able to find the names of the elements.
`MmsVariableSpecification* var = IedConnection_getVariableSpecification(con, &error, dataAttributeReference, fc);`

To get the specification of the first child:

`MmsVariableSpecification* child = MmsVariableSpecification_getChildSpecificationByIndex(var, 0);`
`char* childName = MmsVariableSpecification_getName(child);`

To get the number of childs:
`MmsVariableSpecification_getSize(var)`

Only the top level has no name.

**Comment by Uskok** [comment]
Hi Michael,


Thanks for the tip. It is working.
```

void GetVariableSpecification(MmsVariableSpecification* var)
{
  int varSize = MmsVariableSpecification_getSize(var);
  for(int i = 0; i < varSize; i++)
  {
    MmsVariableSpecification* child = MmsVariableSpecification_getChildSpecificationByIndex(var, i);
    const char* childName = MmsVariableSpecification_getName(child);
    printf("Name: %s\n", childName);
    if(child->type == MMS_STRUCTURE)
      GetVariableSpecification(child);
  }
}

int GetVariableSpecification(IedConnection con, const char* dataAttributeReference, FunctionalConstraint fc)
{
  IedClientError error;
  printf("Get Variable Specification for: %s, FC: %s\n", dataAttributeReference, FunctionalConstraint_toString(fc));

  MmsVariableSpecification* var = IedConnection_getVariableSpecification(con, &error, dataAttributeReference, fc);
  if(error != IED_ERROR_OK)
  {
    printf("Failed to read Variable Specification (error code: %i)\n", error);
    return 1;
  }
  GetVariableSpecification(var);
  return 0;
}
```
