### ISSUE TITLE
[C#/C++] BITSTRING Converter

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#40]
Hi,

I am testing the method (C#): **BitStringFromUInt32**
It calls (C++) **MmsValue_setBitStringFromInteger**(valueReference, intValue);

**The simple code:**

MmsValue value = MmsValue.NewBitString(2);

value.BitStringFromUInt32(0);
Console.WriteLine(value);

value.BitStringFromUInt32(1);
Console.WriteLine(value);

value.BitStringFromUInt32(2);
Console.WriteLine(value);

value.BitStringFromUInt32(3);
Console.WriteLine(value);

**Returns:**

> 00	(0)
> **10	(1)**
> **01	(2)**
> 11	(3)

![image](https://user-images.githubusercontent.com/3512138/33953582-9b100492-e01c-11e7-89d5-5ab7cc3a7bed.png)

**Binary table:**

> 00	(0)
> **01	(1)**
> **10	(2)**
> 11	(3)

**The results should be the same as the binary table. Is this conversion wrong?**

**Comment by mzillgith** [comment]
The MmsValue.ToString method prints the first bit first. The MmsValue_setBitStringFromInteger interprets the first bit as the least significant bit. The the first bit (left) is the least significant bit and the output is correct. In the "binary table" the left bit is the most significant bit. Therefore the order is reversed.

**Comment by IgorMundstein** [comment]
Got it.

Thanks Michael.
