### ISSUE TITLE
No ClientReport method/type available in iec61850.py

### ISSUE THREAD

**Issue by nikunj1222** [mz-automation/libiec61850#424]
I am working on python files to enable reports on the servers.

I am following the C example on how to reports.c. The reporthandler function used in the C has argument of type "ClientReport" check the snippet of C example below.

```
void
reportCallbackFunction(void* parameter, ClientReport report)
{
    LinkedList dataSetDirectory = (LinkedList) parameter;

    MmsValue* dataSetValues = ClientReport_getDataSetValues(report);

    printf("received report for %s with rptId %s\n", ClientReport_getRcbReference(report), ClientReport_getRptId(report));

    if (ClientReport_hasTimestamp(report)) {
        time_t unixTime = ClientReport_getTimestamp(report) / 1000;

#ifdef WIN32
		char* timeBuf = ctime(&unixTime);
#else
		char timeBuf[30];
		ctime_r(&unixTime, timeBuf);
#endif

        printf("  report contains timestamp (%u): %s", (unsigned int) unixTime, timeBuf);
    }

    if (dataSetDirectory) {
        int i;
        for (i = 0; i < LinkedList_size(dataSetDirectory); i++) {
            ReasonForInclusion reason = ClientReport_getReasonForInclusion(report, i);

            if (reason != IEC61850_REASON_NOT_INCLUDED) {

                char valBuffer[500];
                sprintf(valBuffer, "no value");

                if (dataSetValues) {
                    MmsValue* value = MmsValue_getElement(dataSetValues, i);

                    if (value) {
                        MmsValue_printToBuffer(value, valBuffer, 500);
                    }
                }

                LinkedList entry = LinkedList_get(dataSetDirectory, i);

                char* entryName = (char*) entry->data;

                printf("  %s (included for reason %i): %s\n", entryName, reason, valBuffer);
            }
        }
    }

}
```

**When I try to build the same reporthandler in the Python, i was not able to find any iec61850.ClientReport method in iec61850.py file.**
![image](https://user-images.githubusercontent.com/16858646/208084704-8e7de357-8f14-465f-8d2e-1a76ef708290.png)

Is there any other way to acheive and capture the triggered report after activation in python ?

My python code is as mentioned below 👍 

```
from ast import If
import os,sys,time
from asyncio.windows_events import NULL
from winreg import SetValue
from IEC61850lib import iec61850
reportcontrolname = 'TESTP30System/LLN0.RP.urcbA01'
datasetname = 'Dataset1'
datasetpath = 'TESTP30System/LLN0.Dataset1'


def reportCallbackFunction(report):
    dataSetDirectory = iec61850.sLinkedList
    dataSetValues = iec61850.ClientReport_getDataSetValues(report)
    
    print("received report for with rptId %\n", 
          iec61850.ClientReport_getRcbReference(report), iec61850.ClientReport_getRptId(report))
    
    if iec61850.ClientReport_hasTimestamp(report):
        unixTime = iec61850.ClientReport_hasTimestamp(report)/1e3
        buffertime = str(unixTime)
        
        print("report contains timestamp",unixTime,buffertime)
        
        
    if dataSetDirectory:
        for i in range  (iec61850.LinkedList_size(dataSetDirectory)):
            reason = iec61850.ClientReport_getReasonForInclusion(report, i)
            
            if reason != iec61850.IEC61850_REASON_NOT_INCLUDED:
                valBuffer = ''
                print(valBuffer, "no value")
                
                if dataSetValues:
                    value = iec61850.MmsValue_getElement(dataSetValues, i)
                    
                    if value :
                        iec61850.MmsValue_printToBuffer(value,500)
            entry = iec61850.LinkedList_get(dataSetDirectory,i)
            entryName = entry.data
            
            print("included for reason : ", entryName, reason, valBuffer)
                

if __name__=="__main__":
        hostname = "192.20.30.1";
        tcpPort = 102
        if len(sys.argv)>1:
                hostname = sys.argv[1]
        if len(sys.argv)>2:
                port = sys.argv[2]

        con = iec61850.IedConnection_create()
        error = iec61850.IedConnection_connect(con, hostname, tcpPort)
        
        if error == iec61850.IED_ERROR_OK:
            
            #read data set directory
            dataSetDirectory = iec61850.IedConnection_getDataSetDirectory(con,datasetpath,None)
            print(dataSetDirectory)
            
            if error != iec61850.IED_ERROR_OK:
                print('Reading data set directory failed!\\n')
                #goto exit_error
            
            #read data set
            clientDataSet = iec61850.IedConnection_readDataSetValues(con,datasetpath,None)
            print(clientDataSet)
            iec61850.ClientDataSet_getValues()
            
            if clientDataSet == NULL:
                print('failed to read dataset\\n')
                #goto exit_error
                
            #Read RCB values
            rcb = iec61850.IedConnection_getRCBValues(con,reportcontrolname, None)
            print(rcb)
            
            
            
            if error != iec61850.IED_ERROR_OK:
                  print('getRCBValues service error!\\n')
                  #goto exit_error
                  
            #prepare the parameters of the RCP
            iec61850.ClientReportControlBlock_setResv(rcb[0], True)
            iec61850.ClientReportControlBlock_setTrgOps(rcb[0], iec61850.TRG_OPT_DATA_CHANGED | iec61850.TRG_OPT_QUALITY_CHANGED | iec61850.TRG_OPT_GI)
            iec61850.ClientReportControlBlock_setDataSetReference(rcb[0],datasetpath)
            iec61850.ClientReportControlBlock_setRptEna(rcb[0], True)
            iec61850.ClientReportControlBlock_setGI(rcb[0], True)
            
            # Configure the report receiver
            iec61850.IedConnection_installReportHandler(con,reportcontrolname, iec61850.ClientReportControlBlock_getRptId(rcb[0]),
                                                        reportCallbackFunction(rcb[0]), None)
            
            
            # Write RCB parameters and enable report
            iec61850.IedConnection_setRCBValues(con, rcb[0], iec61850.RCB_ELEMENT_RESV | iec61850.RCB_ELEMENT_DATSET | iec61850.RCB_ELEMENT_TRG_OPS | 
                                                iec61850.RCB_ELEMENT_RPT_ENA | iec61850.RCB_ELEMENT_GI, True)
            
            if error != iec61850.IED_ERROR_OK:
                print('setRCBValues service error!\\n')
                #goto exit_error
                
            time.sleep(1)
            
            # Trigger GI Report
            iec61850.ClientReportControlBlock_setGI(rcb[0], True)
            iec61850.IedConnection_setRCBValues(con, rcb[0], iec61850.RCB_ELEMENT_GI, True)
            
            if error != iec61850.IED_ERROR_OK:
                print('Error triggering a GI report \\n', error)
                #goto exit_error
            
            running = True    
            while running:
                time.sleep(1)
                
                conState = iec61850.IedConnection_getState(con)
                
                if conState != iec61850.IED_STATE_CONNECTED:
                    print('Connection close by server \\n')
                    running = False
                
            # disable reporting
            
            iec61850.ClientReportControlBlock_setRptEna(rcb, False)
            iec61850.IedConnection_setRCBValues(con, rcb[0], iec61850.RCB_ELEMENT_RPT_ENA, True)
```

**Comment by mbourhis** [comment]
Hi,
please note that the Python wrapper is experimental.

For registering the callbacks, we use extra objects ('RCBHandler' and 'RCBSubscriber') that are only defined for the Python wrapper (libiec61850/pyiec61850/eventHandlers/).

And the 'RCBHandler' owns a ClientReport object.

In this PR [1], 
I give an example of an RCB subscriber, that handles ClientReport.

Here an extract of the output:

```
New received RCB: simpleIOGenericIO/LLN0.RP.EventsRCB01
        DataSet name: simpleIOGenericIO/LLN0$Events
        Report id: Events1
        Sequence num: 2
        Timestamp in millsec: 1674488131896
        DataSet size: 4
        MMS value: False
        Reason for inclusion: integrity
        MMS value: False
        Reason for inclusion: integrity
        MMS value: False
        Reason for inclusion: integrity
        MMS value: False
        Reason for inclusion: integrity

New received RCB: simpleIOGenericIO/LLN0.BR.Measurements01
        DataSet name: simpleIOGenericIO/LLN0$Measurements
        Report id: Measurements
        Sequence num: 32
        Timestamp in millsec: 1674488131896
        DataSet size: 8
        MMS value: -0.971513032913208
        Reason for inclusion: data-change
        MMS value: other type
        Reason for inclusion: not-included
        MMS value: -0.3254937529563904
        Reason for inclusion: data-change
        MMS value: other type
        Reason for inclusion: not-included
        MMS value: 0.6197829842567444
        Reason for inclusion: data-change
        MMS value: other type
        Reason for inclusion: not-included
        MMS value: 0.9952340722084045
        Reason for inclusion: data-change
        MMS value: other type
        Reason for inclusion: not-included

```

I hope this example can help you.

[1] https://github.com/mz-automation/libiec61850/pull/430

**Comment by nikunj1222** [comment]
@mbourhis thanks a lot for your example. It clears lots of things for me.

The example file produced by @mbourhis can be found here : https://github.com/mz-automation/libiec61850/blob/5f767ad03eded2e34d22a7a976e438e8d372de27/pyiec61850/examples/rcbSubscriptionExample.py

**Comment by nikunj1222** [comment]
> For registering the callbacks, we use extra objects ('RCBHandler' and 'RCBSubscriber') that are only defined for the Python wra

Hi @mbourhis it seems while building 1.5.1 for windows pyWrap function was not built and hence i am getting this error :

`Exception has occurred: AttributeError
module 'IEC61850lib.iec61850' has no attribute 'pyWrap_IedConnection_getRCBValues'
  File "F:\DEV\PythonCode\Python_IEC61850\ReportsControl.py", line 142, in subscribe
    l_return_value = iec61850.pyWrap_IedConnection_getRCBValues(self._connection, i_report_control_block_ref, None)
  File "F:\DEV\PythonCode\Python_IEC61850\ReportsControl.py", line 239, in <module>
    rcb_subscriber_1.subscribe(con, L_RCBREF_STATUS)
AttributeError: module 'IEC61850lib.iec61850' has no attribute 'pyWrap_IedConnection_getRCBValues'`

Is there anything special to be done to build the python lib to have pyWrap ?

Thanks for your support on the matter.

Nikunj Patel

**Comment by mbourhis** [comment]
Hi @nikunj1222,
pyWrap* are wrapping functions that prevent deadlocks.
These functions have been added in May 2022, see:
 * the commit  https://github.com/mz-automation/libiec61850/commit/8b43a644b13fdcc18463cee150eeb6613fc29ae7
 * and the PR, that contains details: https://github.com/mz-automation/libiec61850/pull/383

These functions are available in the main branch: 'v1.5'.
But, the last release '1.5.1' is unfortunately too old (march 2022).
I don't know when the next release is scheduled.

**Comment by nikunj1222** [comment]
@mbourhis thanks a lot for your quick reply.

I checked the main branch it is available and i am trying to build it for windows. Unfourtunately it is a tricky job to build for windows.

Do you have any suggestion on building for windows on x64 platform ?

Once again thanks for your quick response.

**Comment by mbourhis** [comment]
No,  sorry, I never use Window$

**Comment by nikunj1222** [comment]
@mbourhis 

Windows-10 64bit 
Python 3.9.11 64bit
Visual Basic 2017 / 2019

I have tried to build python libraries using CMAKE GUI and Visual Basic 2017 / 2019. I have tried to build both 64bit and 32bit libraries.
The building works successfully but when i try to IMPORT in python i get this error :

`ImportError: DLL load failed: %1 is not a valid Win32 application`

I looked it up and found that this error occurs due to mistmatch between 64bit python and 32bit build libraries. But I tried to build the python library in 64bit and still I get this error.

I tried this on 3 different PC and all of them gave me same error. Where as when I previously build my python libraries using LibIec618501.5.1 I did not get this error.

**Comment by nikunj1222** [comment]
@mbourhis 

Hi, I have managed to build the library for windows.

I have started reading reports dataset. Check the below output :

`RCBSubscription: create subscription for: 'TESTP30System/LLN0.RP.urcbA01'

New received RCB: TESTP30System/LLN0.RP.urcbA01
        DataSet name: TESTP30System/LLN0$Dataset1
        Report id: TESTP30System/LLN0$RP$urcbA
        Sequence num: 0
        Timestamp in millsec: 1675431187665
        DataSet size: 14
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 0
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 1
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 2
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 3
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 4
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 5
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 6
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 7
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 8
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 9
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 10
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF9F0> 11
STRUCTURE
        Reason for inclusion: GI
<Swig Object of type 'MmsValue *' at 0x0000017848CAF990> 12
STRUCTURE
        Reason for inclusion: GI
        MMS value: False
        Reason for inclusion: GI`

However you can see that when we add whole DO in the DATASET FCDA, the script detects it as structure. (DO with Stval, q and t)

Since I am a electrical engineer, I would like to know your opinion or suggestion on how to read the whole DO in the FCDA.

Your kind suggestion woule be highly appreciated.

Thanks
Nikunj PATEL
