### ISSUE TITLE
Reporting behaviour in version 1.1.1

### ISSUE THREAD

**Issue by Morand84** [mz-automation/libiec61850#45]
Hi,
I noticed a strange behaviour that was not present in version 1.0.
It occous when I use reporting in the client api, sometimes ( not always ) when the callback is called the :

MmsValue* dataSetValues = ClientReport_getDataSetValues(report);

gave me the previous (N-1)  MmsValue, like it has not been correctly updated in memory.
The  ClientReport_getSeqNum(report) gave me correct SeqNum, identical to IED Scout sniffer, but the mms values were not updated.
I confirm that everything worked perfectly on version 1.0

I tried to check differences in the libraries, but I have not found anything for now..

Has anybody seen something similar? Thanks a lot!

**Comment by Morand84** [comment]
I forgot. Platform : Windows 7 , C API in Visual Studio 2013 32bit

**Comment by mzillgith** [comment]
I suspect that the MmsValue_update function fails for some reason. There has been a change in this commit 15ec6c7a7c56b13c6f7587312231e44774204e36 . Maybe you can revert this commit and see if it works.

**Comment by Morand84** [comment]
Yes, this is the problem. 

Now it's working fine, I'm not losing anything from this SIPROTEC5 relay. 
If you are interested I can sniff with wireshark the reporting packages that always fails and the packages that always works to check differences ..

Thanks a lot.

**Comment by mzillgith** [comment]
It would be great if you could sniff and post the packages that fails.

**Comment by Morand84** [comment]
Sure!
I'm working on SIPROTEC5 7SA87
This is a reporting message of the  RCB containing an electrical switch position.


In this case I've got an electrical switch open (reporting correctly recognize):

![switch_open](https://user-images.githubusercontent.com/35305126/34827811-b22d2c24-f6db-11e7-8ce3-10cc7641eee3.jpg)


Then I send a command of close, so the switch it's moving.. (reporting correctly recognize):

![switch_in_movement](https://user-images.githubusercontent.com/35305126/34827828-c114ea60-f6db-11e7-991b-c177d692b5b0.jpg)

Then it's closed.. (reporting correctly recognize):

![switch_closed](https://user-images.githubusercontent.com/35305126/34827835-c88d8266-f6db-11e7-8ff8-c7cfa7035199.jpg)

Then I cause an opening by trip (reporting Not recognize):

![switch_open_by_protection_trip](https://user-images.githubusercontent.com/35305126/34827857-da7f6494-f6db-11e7-95e6-f1c9bd7fca84.jpg)

I see the message it's quite different in this last case...

Hope I've been helpful.

**Comment by pavel-ch** [comment]
Hello,
to make Wireshark to dissect PDU correctly, fill:
Under Edit/Preferences/Protocols/PRES/Edit... User Context List/
and fill in the following to a new line in the table:
Context Id: 3
Syntax Name OID: 1.01.9506.2.3
![image](https://user-images.githubusercontent.com/771816/34829033-b62bc7dc-f6df-11e7-9a54-75458aed94f0.png)

You can see correctly parsed 61850 packets then.
And, anyway, the best way is to extract packets and send in pcap format instead of screenshots.

br Pavel

**Comment by Morand84** [comment]
Thanks, now it parse.
Here it is the pcap file.
[libiec61850_111_reporting_probl.zip](https://github.com/mz-automation/libiec61850/files/1622936/libiec61850_111_reporting_probl.zip)

**Comment by mzillgith** [comment]
Thanks.
I guess the reason was the change of the size of the octet-string ("owner" I think). I updated the code to accept the different size octet string.
