### ISSUE TITLE
IedConnection_writeFloatValue returns IED_ERROR_ACCESS_DENIED?

### ISSUE THREAD

**Issue by MaoniinoaM** [mz-automation/libiec61850#450]
Hi, Libiec61850 team,
I try test the python interface:
theVal = "simpleIOGenericIO/GGIO1.AnIn1.mag.f"
theValType = iec61850.IEC61850_FC_MX

err = iec61850.IedConnection_writeFloatValue(con, theVal, theValType, 25.0)

the err always returns IED_ERROR_ACCESS_DENIED.  I'm confused what's wrong. Can you help give any hints?

**Comment by nikunj1222** [comment]
theVal = "simpleIOGenericIO/GGIO1.AnIn1.mag.f"
theValType = iec61850.IEC61850_FC_MX

The Val value or The ValType might not be matching.... This is a common mistake we generally make.

IED_ERROR_ACCESS_DENIED is due to invalid request or DO object path is not writeable...

**Comment by MaoniinoaM** [comment]
> 

Thanks for the response.
