### ISSUE TITLE
Process terminated. A callback was made on a garbage collected delegate of type 'iec61850dotnet!IEC61850.Client.ControlObject+InternalCommandTerminationHandler::Invoke'

### ISSUE THREAD

**Issue by epasinetti** [mz-automation/libiec61850#459]
I have a problem using in my C# application this code, after calling few times, I obtain a bad error, I have tried to Dispose control object after using it but the error is still present. 

        if (control.SelectWithValue(bStatus))
        {
            if (!control.Operate(bStatus))
                Console.WriteLine("operate failed!");
            else
                Console.WriteLine("operated successfully!");
        }
        else
            Console.WriteLine("Select failed!");
        break;

Process terminated. A callback was made on a garbage collected delegate of type 'iec61850dotnet!IEC61850.Client.ControlObject+InternalCommandTerminationHandler::Invoke'.

![image](https://github.com/mz-automation/libiec61850/assets/8982850/5924915a-71fb-4899-86db-ed32e2272881)

**Comment by mzillgith** [comment]
What version (git commit) of the library are you using?

**Comment by epasinetti** [comment]
commit version 1.5

**Comment by mzillgith** [comment]
If you mean release version 1.5 then that's quite old.

Can you try to upgrade to the head of the v1.5 branch? (https://github.com/mz-automation/libiec61850/commit/30fec0a79faea49190ef2c78e0dce340c92ef44f)

**Comment by epasinetti** [comment]
sorry but I've tried 1.5.2 and also 1.6 develop but the problem still exist

![image](https://github.com/mz-automation/libiec61850/assets/8982850/45fb94a7-5a7e-4881-ad43-2c4227c78b9e)
