### ISSUE TITLE
BufferedRCBs error

### ISSUE THREAD

**Issue by angwangiot** [mz-automation/libiec61850#46]
1. compile with cygwin + arm-mingw32ce-gcc (v0.59.1) for WinCE.
2. unrecognized command line option "-mno-unaligned-access", so unaligned access on arm(arm926ej-s).
3. the buffer report on the iedserver is enabled by the client.
4. error in reporting.c/sendNextReportEntry()/ add data set value elements/ MmsValue_getSizeInMemory()/case MMS_ARRAY case MMS_STRUCTURE /self->value.structure.components[i]  and program exit.

**Comment by mzillgith** [comment]
If your gcc doesn't support the "-mno-unaligned-access" option maybe you need to use another option to force the compiler to generate correct code for your platform. I guess one of the "-mcpu=" or "-march=" options may do it.

**Comment by angwangiot** [comment]
Thanks
I added the "-mcpu=arm926ej-s" and"-march=armv5" options, but the error still exist.

**Comment by mzillgith** [comment]
Can you use a newer gcc? I think gcc 4.8 should do as it has the "-mno-unaligned-access" option.

**Comment by angwangiot** [comment]
Gcc 4.8 has the "-mno-unaligned-access" option, but cegcc (http://cegcc.sourceforge.net/) stopped updating in October 2009, the latest version is 0.59.1, which uses gcc4.4.

**Comment by mzillgith** [comment]
Are you sure the problem is caused by unaligned memory access? I have tried with an embedded linux system that identified the processor as "ARM926EJ-S rev 5 (v5l)" and also used gcc 4.4. The buffered reporting worked without problem despite the unaligned memory.

**Comment by angwangiot** [comment]
Thank you very much for your reply. 
I made the same test on the linux system using s3c2440 CPU, and then I got a segmentation fault when the value of the data set was a struct or array.
Can you try again with this CFG file?
[model.zip](https://github.com/mz-automation/libiec61850/files/1814396/model.zip)

**Comment by angwangiot** [comment]
I learned from the Internet that the older ARM processors do not support unaligned memory access on hardware. On older processors, such as ARM9 family based processors, an unaligned load had to be synthesised in software.  
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka15414.html

**Comment by mzillgith** [comment]
I tried with your config file on the ARM926EJ-S linux box. I enabled the BRCB and waited some time but there was no problem.
If you have a debugger on your board, can you provide a stack trace?

**Comment by mzillgith** [comment]
On another linux system with ARM v4 (I can see the problem). Seems indeed to be a memory alignment problem. There is a workaround for the linux system:
`echo 2 > /proc/cpu/alignment`
will instruct the linux kernel to fix the problem.

**Comment by angwangiot** [comment]
Yes, this problem can be solved in this way on embedded Linux system.But I want to compile it on the WinCE system, and it doesn't seem to be feasible.Can you help me to solve it in other ways, please?  For example, the mandatory conversion of the pointer is changed to a copy of the memory through the memcpy function.
Thank you.

**Comment by mzillgith** [comment]
I updated the development branch. Please check if it works with these changes.

**Comment by angwangiot** [comment]
Thank you very much for your help. I will test it tomorrow.
