### ISSUE TITLE
Memory leak in setGoID, setGoCbRef and setDataSetRef

### ISSUE THREAD

**Issue by zmatthias** [mz-automation/libiec61850#464]
Hello, _StringUtils_copyString_ allocates memory for a new string. The functions: _setGoID_, _setGoCbRef_ and _setDataSetRef_ do not free memory for an existing string. My goal was to build a fuzzer using iec61850. For that, I needed to change setGoID, setGoCbRef and setDataSetRef very often and fast. This caused a memory overflow. Calling _GoosePublisher_create_ and _GoosePublisher_destroy_ was not an option because it takes too much time.

I solved the memory leak quick and dirty for myself by adding these lines: https://github.com/mz-automation/libiec61850/pull/374/commits/5bffa4a17246a4974982ef05fcaeb1f493cfcd70
But the pull request failed for some reason.

**Comment by mzillgith** [comment]
Thank you for the hint. I will integrate the frees into the mentioned functions.
