### ISSUE TITLE
fetch dynamic model error under array node 

### ISSUE THREAD

**Issue by xiezhaokai** [mz-automation/libiec61850#468]
Here I have an ied model shown as below (by IEDScout)

![array-example](https://github.com/mz-automation/libiec61850/assets/15663840/e84b9f5c-e9c8-458d-ae90-01e815e6ea8c)
Under node "PQPQLD1/MHAI4.HRPhV.phsAHar" is an array. 
But When I use `IedConnection_getDataDirectoryByFC` to walk throught the data model the same way as example code "iec61850_client_example2" shows.   The recursive function ends at the node unexpectedly. 
The breakpoint in debug mode  shows that the returned LinkedList has a "null next " . 

![code](https://github.com/mz-automation/libiec61850/assets/15663840/6ca60d69-11d5-46c0-a061-dacecb25e64f)

![null_next](https://github.com/mz-automation/libiec61850/assets/15663840/39dcde24-4955-43ed-83e0-f85c8fe137da)

 Am I used the wrong API to walk throught deeply under a array node?  The version I used is "1.5.1".

**Comment by chenjing1294** [comment]
@xiezhaokai Hi, how do you solve this problem? Even if you use "testComplexArray/MHAI1.HA.phsAHar(0)" I still can't get DataAttribute

**Comment by xiezhaokai** [comment]
A workaround way I used  but may not efficient enough is  fetching   `MmsVariableSpecification`  of the node recursively through `MmsVariableSpecification_getChildSpecificationByIndex`
