### ISSUE TITLE
Download a file inside a directory

### ISSUE THREAD

**Issue by jkancio** [mz-automation/libiec61850#51]
I'm trying to use this library to download files from an IED with 61850 File Transfer protocol. I used GetFile() method from IedConnection class of IEC61850ClientAPI code.

It runs ok for files on the root path, but it does not work for files in a sub-directory.
How do I pass the full path name to GetFile() method  in order to download these files?

**Comment by mzillgith** [comment]
I tried with several IEDs and it worked with the "/" as path separator. Some device might require a "\" as path separator.

**Comment by darkjhesus** [comment]
Dear jkancio, could you share your code to download files from IED?
