### ISSUE TITLE
function ControlObjectClient_select here the "$SBO"node name should be "$SBOw"

### ISSUE THREAD

**Issue by tangkai-prc** [mz-automation/libiec61850#520]
https://github.com/mz-automation/libiec61850/blob/519b0208cc79d1af09d5ca40fb9ad1fd93822e93/src/iec61850/client/client_control.c#L895

**Comment by mzillgith** [comment]
The code is correct. If you need select-with-value ("SBOw") then your application has to call `ControlObjectClient_selectWithValue ` instead of `ControlObjectClient_select`
