### ISSUE TITLE
IEC 61869-9 support

### ISSUE THREAD

**Issue by Alexanderstaehle** [mz-automation/libiec61850#528]
Hi everyone :)

I read that IEC 61869-9 is superseding IEC 61850-9-2LE and that IEC 61869-9 is backwards compatible with IEC 61850-9-2LE communication.

Would that mean that a system using IEC 61869-9 would be compatible with libiec61850 when it comes to SVs?
Also:
- How is IEC 61850-9-3 (PTP) handled?

Thank you in advance for any guidance!

**Comment by mzillgith** [comment]
Regarding SV the library is compatible with the current version of IEC 61869-9. There is a new version of IEC 61869-9 coming that has some small changes that are not yet supported by libiec61850. But the library should still be able to handle such SV messages.

Regarding PTP this is out of scope of the library. Usually this is handled by the OS.
