### ISSUE TITLE
How to enable keepalive ?

### ISSUE THREAD

**Issue by codebuks** [mz-automation/libiec61850#56]
I use libiec61850 in Linux, I wonder how to enable the keepalive,
In `stack_config.h` , there is a define:
`#define CONFIG_ACTIVATE_TCP_KEEPALIVE 1`
when `TcpServerSocket_create` or `Socket_connect` is called, the above define will be judged, if it is defined `activateKeepAlive` will be called.
But in `socket_linux.c`,  in the `activateKeepAlive` function, there are two defines `SO_KEEPALIVE` and `TCP_KEEPCNT`, 
**Do I need to define them by myself?**
```
static void
activateKeepAlive(int sd)
{
#if defined SO_KEEPALIVE
    int optval;
    socklen_t optlen = sizeof(optval);

    optval = 1;
    setsockopt(sd, SOL_SOCKET, SO_KEEPALIVE, &optval, optlen);

#if defined TCP_KEEPCNT
    optval = CONFIG_TCP_KEEPALIVE_IDLE;
    setsockopt(sd, IPPROTO_TCP, TCP_KEEPIDLE, &optval, optlen);

    optval = CONFIG_TCP_KEEPALIVE_INTERVAL;
    setsockopt(sd, IPPROTO_TCP, TCP_KEEPINTVL, &optval, optlen);

    optval = CONFIG_TCP_KEEPALIVE_CNT;
    setsockopt(sd, IPPROTO_TCP, TCP_KEEPCNT, &optval, optlen);
#endif /* TCP_KEEPCNT */

#endif /* SO_KEEPALIVE */
}
```

**Comment by mzillgith** [comment]
It is only required to set
  `#define CONFIG_ACTIVATE_TCP_KEEPALIVE 1`
The `SO_KEEPALIVE` and `TCP_KEEPCNT`are defined in some linux header files. It is only verified that they are existing.

**Comment by codebuks** [comment]
@mzillgith thank you very much ， I  see.
