### ISSUE TITLE
Memory growth when using Report

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#57]
Hi @mzillgith 

I was testing report. I realized that some IED can disable a report without a disconnection. I need to constantly check if the report is enabled. I noticed a memory growth while checking if the report is enabled. This occurs with or without receiving reports. Is this way to verify and enable report correct?

	while (running)
	{
		ReportControlBlock report = connection.GetReportControlBlock(address);
		report.GetRCBValues();

		bool isReportEnabled = report.GetRptEna();

		if (!isReportEnabled)
		{
			//var a = report.GetOptFlds();
			//var b = report.GetTrgOps();
			//var c = report.GetIntgPd();
			//var d = report.GetGI();
			//var e = report.GetPurgeBuf();
			//var f = report.GetResv();

			//report.SetOptFlds();
			//report.SetTrgOps();
			//report.SetEntryID();

			report.InstallReportHandler(ReportHandler, point);
			report.SetRptEna(true);
			report.SetRCBValues();
		}
	}  

I was also thinking of using the method connection.ReadValue instead of report.GetRCBValues to check if RptEna attribute is true or false.

Can you check if a memory leak is occurring when methods are called?

Obs: Wireshark log attached.

[wireshark.zip](https://github.com/mz-automation/libiec61850/files/1952717/wireshark.zip)

**Comment by mzillgith** [comment]
Indeed there is a memory leak because of a missing destructor for ReportControlBlock and so the native resource is not released. Should be fixed now.

Anyway this is a really strange behavior of the device. The device should not disable the report control block and this kind of polling should not be required. Because the idea of reporting is to avoid the need for polling. Do you know why the device behaves like this?

If it is really required I would recommend to put the line 
`ReportControlBlock report = connection.GetReportControlBlock(address);` 
outside of the while loop. This way you would avoid creating a new instance of ReportControlBlock for every request. Or polling the RptEna attribute with ReadValue as you suggested would be an even more simple solution.

**Comment by IgorMundstein** [comment]
> Indeed there is a memory leak because of a missing destructor for ReportControlBlock and so the native resource is not released. Should be fixed now.

Ok. I will test it.

> Anyway this is a really strange behavior of the device. The device should not disable the report control block and this kind of polling should not be required. Because the idea of reporting is to avoid the need for polling. Do you know why the device behaves like this?

When some old devices has configuration changed by own software. The reports are disabled and this does not cause a disconnection. Consequently, I do not have a trigger telling me that the report is not signed. So, I have to check periodically to ensure integrity.

> If it is really required I would recommend to put the line
ReportControlBlock report = connection.GetReportControlBlock(address);
outside of the while loop. This way you would avoid creating a new instance of ReportControlBlock for every request. Or polling the RptEna attribute with ReadValue as you suggested would be an even more simple solution.

I downloaded the latest version. However, I am no longer able to generate the C ++ dll. I did the same steps as earlier. I builded iec61850 project. There were no errors, but only iec61850.exp and iec61850.lib files were generated.

I tried to build all the projects and I did not succeed with iec61850-shared project. 

![image](https://user-images.githubusercontent.com/3512138/39374010-e20bd6c4-4a1f-11e8-84d4-fa7790075c1b.png)

I know that MmsValue_cloneToBuffer method has been modified, but what am I missing?

**Comment by mzillgith** [comment]
Thanks for the explanation. As I know the device should close connections when the configuration changes.

I have no problem building the projects in Visual Studio. Did you clone the latest from the v1.2 branch?

**Comment by IgorMundstein** [comment]
> Thanks for the explanation. As I know the device should close connections when the configuration changes.

Yeah. This is the IED correct operation. However, there are always exceptions. 

> I have no problem building the projects in Visual Studio. Did you clone the latest from the v1.2 branch?

Yes I did. I always follow the same steps. The last builded version that I have is 1.1.2.0. I downloaded it on March 13. Something has changed since then.

**Comment by mzillgith** [comment]
Ok. As I said it worked for me.

I used commit da17f82 (latest in github)

I create a subfolder "build". In this folder I run
`cmake -G "Visual Studio 15 2017" ..`

Then I load the generated solution in Visual Studio and can build everything.

**Comment by IgorMundstein** [comment]
Hum. I use: 
cmake -G "Visual Studio 14 2015 Win64"
Configuration: Release (x64)

I tried using Debug Configuration and it worked !

Have you changed something in Debug configuration and forgot to replicate in Release configuration?

**Comment by mzillgith** [comment]
I see. I have the same problem when using the "Release" configuration.
It is resolved when I remove the "inline" from the function signature of MemoryAllocator_getAlignedSize in simple_allocator.c
Yet I don't understand why this doesn't work because this is an internal function.

**Comment by IgorMundstein** [comment]
I see. It worked too for me when I removed the "inline".

Programming is a box of surprises. :)
