### ISSUE TITLE
Timestamp change and goose publishing

### ISSUE THREAD

**Issue by davideandreuzza** [mz-automation/libiec61850#58]
Hello,
I have noticed a strange behaviour during the transmission of goose messages (from a server using libiec61850), when only timestamp changes in the referenced dataset. It happens the following (output printed from the receiving server using libiec61850, but wireshark shows the same):

received GOOSE from gcb: MODULO1/LLN0$GO$gcb_Segnalaz
**stNum: 8**, sqNum: 0, timeToLive: 1500, timestamp: 1496921282.235
{false,0000000000000,20170608105249.383Z},{false,0000000000000,20170608105249.735Z},{false,0000000000000,20170608105249.696Z},{false,0000000000000,20170608105249.545Z},{true,0000000000000,**20170608112758.848Z**},{false,0000000000000,20170608105249.795Z},{false,0000000000000,20170608105249.236Z},{false,0000000000000,
19700101000000.000Z},{false,0000000000000,**20170608105249.151Z**},{false,0000000000000,20170608105249.844Z},{false,0000000000000,2017060
8105249.668Z}}

received GOOSE from gcb: MODULO1/LLN0$GO$gcb_Segnalaz
**stNum: 8**, sqNum: 1, timeToLive: 1500, timestamp: 1496921282.235
{false,0000000000000,20170608105249.383Z},{false,0000000000000,20170608105249.735Z},{false,0000000000000,20170608105249.696Z},{false,0000000000000,20170608105249.545Z},{true,0000000000000,**20170608112802.704Z**},{false,0000000000000,20170608105249.795Z},{false,0000000000000,20170608105249.236Z},{false,0000000000000,
19700101000000.000Z},{false,0000000000000,**20170608112802.755Z**},{false,0000000000000,20170608105249.844Z},{false,0000000000000,2017060
8105249.668Z}}

As you can see the stNum remains the same but there are some value change (timestamp change).
The standard IEC 61850-7-2, part 18.2.3 says: "A GOOSE message shall at least be sent each time when a value from one or more members referenced by the data-set change". It does not mention the fact that the data attribute must have dchg or qchg set to true. In my publisher server CID, in fact, the timestamps don't have any trigger option specified.

**Comment by mzillgith** [comment]
Hi,
This behavior is expected given the current implementation. The second message is the automatic retransmission for the event that caused the first message (stNum remains the same, but sqNum is increased - that means it is the first retransmission). For retransmission the server uses the current values of the data set members. And when the server updates the timestamps then the new timestamps are used in the retransmission. I am not sure if this behavior is as intended by the standard and what I would expect is that the timestamps remain the same as in the original message. But for the application of GOOSE only the change of the state (and quality if defined as a trigger) matters.

**Comment by davideandreuzza** [comment]
Thanks for you response. 
I understand that the current implementation of goose transmission is based on triggers (data change and quality change). What I would point out, in the perspective of library improvement, is that the standard (part 7-2) says that no triggers may be considered, and that any change of value in the dataset produces a goose event.
This is shown also here: http://iec61850.tissue-db.com/tissue/1613

**Comment by mzillgith** [comment]
Thank you for the hint with the tissue. I was not aware of it. Reading the answer there I guess that changing the timestamp is also considered as a value change. I will try to verify this with the standard and will have a look what has to be done to change the implementation

**Comment by davideandreuzza** [comment]
Thanks
