### ISSUE TITLE
Is that possible to keep the events on buffered report ?

### ISSUE THREAD

**Issue by JianWei8720** [mz-automation/libiec61850#59]
Everyday there are some events generate in my device,  only when the client enable the buffered report the device will report events to client. But  if power outage all there events will lost due to all the events was buffered in memory.  Have any ways to avoid this situation ?

**Comment by mzillgith** [comment]
As I see according to the standard the report buffer doesn't have to be preserved after device restart. In this case I would recommend to use the log service.
