### ISSUE TITLE
Problem testing Goose Publisher/Subscriber examples on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by gopchandani** [mz-automation/libiec61850#61]
Hi! 

I was able to compile the goose_publisher and goose_subscriber under the examples. When I run the programs, I don't see the subscriber receiving any messages. I do see a three packets generated by the publisher on the interface.

Could you kindly point to how to test if the subscriber is working correctly? There is nothing printed on the shell and I don't see any log files in its folder.

Thanks,

-
Rakesh

**Comment by mzillgith** [comment]
Hi,
In linux you cannot see the messages you sent on the same interface. So if publisher and subscriber are on the same linux box using the same ethernet interface this doesn't work.

**Comment by gopchandani** [comment]
Do you have any suggestion on how should I test it?

**Comment by mzillgith** [comment]
You can run the publisher and subscriber on two different machines.

**Comment by gopchandani** [comment]
Running pub and sub on different interfaces worked out. I used mininet to run them on the same machine instead of running them on different machines.

**Comment by fouzhe** [comment]
> Running pub and sub on different interfaces worked out. I used mininet to run them on the same machine instead of running them on different machines.

Hi, could you please tell me how to run pub and sub on different interfaces? Thanks!

**Comment by PreethiSreenath** [comment]
Can anyone help in testing the sample goose_subscriber with the goose publishing from IEDScout or some other iec61850 server which publishes goose.? The sample goose subscriber works only with the sample goose publisher given in the library. Please help

**Comment by cliff101532** [comment]
> Running pub and sub on different interfaces worked out. I used mininet to run them on the same machine instead of running them on different machines.

Hi，I also want to build a goose example on my mininet. I want to know how did you run the example on your miniet.

**Comment by cliff101532** [comment]
> Hi, In linux you cannot see the messages you sent on the same interface. So if publisher and subscriber are on the same linux box using the same ethernet interface this doesn't work.

Can my two machine under the same vlan receive the message with ethernet? Or they must under a same bus.
