### ISSUE TITLE
IedConnection_writeObject(...) won't work

### ISSUE THREAD

**Issue by arthurazs** [mz-automation/libiec61850#64]
I'm running **iec61850_client_example1** and **server_example_basic_io**.

`IedConnection_writeObject(...)` always outputs

> failed to write simpleIOGenericIO/GGIO1.NamPlt.vendor!

Is it supposed to happen?

I followed the [client tutorial](https://libiec61850.com/libiec61850/documentation/iec-61850-client-tutorial/) but I can't get `IedConnection_writeObject(...)` to work either. Am I missing something?

**Comment by arthurazs** [comment]
Nevermind!

To enable access I had to run the **server_example_write_handler**. I still used **iec61850_client_example1** but I changed the **dataAttributeReference** to:

    value = MmsValue_newFloat(13);
    IedConnection_writeObject(con, &error, "ied1Inverter/ZINV1.OutVarSet.setMag.f", IEC61850_FC_SP, value);

That should work :)

**Comment by mzillgith** [comment]
Write only works when the server allows it. In general it is only used for settings (SP) or setting groups (SE).
So the example I provide is not very good. I cannot imagine a situation where changing the "vendor" of a device is useful ;-)

**Comment by arthurazs** [comment]
I'm new in the area, still a lot to learn.

I'll have that in mind, thank you!
