### ISSUE TITLE
IsoConnectionParameters.UsePasswordAuthentication(string password) doesn't always have effect

### ISSUE THREAD

**Issue by jpeltonen** [mz-automation/libiec61850#7]
example .NET code:

```
con = new IedConnection();
IsoConnectionParameters parameters = con.GetConnectionParameters();
parameters.UsePasswordAuthentication("password");
con.Connect(hostname, 102); 
```

sometimes shows nothing in Wireshark (authentication: False):

![authentication](https://cloud.githubusercontent.com/assets/22810621/24447652/64af4f52-147a-11e7-89a9-d297935e0f9d.png)

When succesfull shows this:

![authentication_pass](https://cloud.githubusercontent.com/assets/22810621/24448007/798d030a-147b-11e7-9249-61967e03c510.png)

using libiec61850-1.0 in Windows 7.

**Comment by mzillgith** [comment]
Hi, I think the problem was the garbage collector removing the IsoConnectionParameters object required for the password authentication. I added an internal reference and now the problem seems to be solved.
