### ISSUE TITLE
[C#] [Server layer] Multiple Servers. Data attribute upgrade only works on last one.

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#70]
Hi,

I'm testing the Server layer. I'm trying to start 1 or more servers. I can start them on different port or IP (SetLocalIpAddress). However, when I update data attributes, this only works on the **last started server**. Consequently, I can no longer update the data attributes of the first server.

	IedModel model = ConfigFileParser.CreateModelFromConfigFile(cfgFile);

	IedServer ied1 = new IedServer(model);
	ied1.Start(102);

	IedServer ied2 = new IedServer(model);
	ied2.Start(103);

	// It doesn't work
	ied1.LockDataModel();

	DataAttribute valueDataAttribute = model.GetModelNodeByObjectReference(valueAddress) as DataAttribute;
	ied1.UpdateFloatAttributeValue(valueDataAttribute, value);

	DataAttribute qualityDataAttribute = model.GetModelNodeByObjectReference(qualityAddress) as DataAttribute;
	ied1.UpdateQuality(qualityDataAttribute, quality);

	DataAttribute timestampDataAttribute = model.GetModelNodeByObjectReference(timestampAddress) as DataAttribute;
	ied1.UpdateUTCTimeAttributeValue(timestampDataAttribute, timestamp);

	ied1.UnlockDataModel();

	// It works
	ied2.LockDataModel();

	DataAttribute valueDataAttribute = model.GetModelNodeByObjectReference(valueAddress) as DataAttribute;
	ied2.UpdateFloatAttributeValue(valueDataAttribute, value);

	DataAttribute qualityDataAttribute = model.GetModelNodeByObjectReference(qualityAddress) as DataAttribute;
	ied2.UpdateQuality(qualityDataAttribute, quality);

	DataAttribute timestampDataAttribute = model.GetModelNodeByObjectReference(timestampAddress) as DataAttribute;
	ied2.UpdateUTCTimeAttributeValue(timestampDataAttribute, timestamp);

	ied2.UnlockDataModel();

Please can you check?

**Comment by mzillgith** [comment]
Hi,
This cannot work. The IedModel can only be used by a single IedServer instance. This is because the IedServer has an internal data value cache and stores references to values in this cache into the DataAttribute instances of the IedModel when being created. So in your case when creating the second instance the already existing references will be replaced by the second instance.
If you want to use multiple instances of IedServer you also need multiple instances of IedModel.

**Comment by IgorMundstein** [comment]
Understood. 

Thanks Michael.
