### ISSUE TITLE
[C#] Report control block (Owner)

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#79]
Hi @mzillgith 

Could you publish the **ClientReportControlBlock_getOwner** method?

**Comment by IgorMundstein** [comment]
@mzillgith 

The new published method **ClientReportControlBlock_getResvTms** has worked.

However, **ClientReportControlBlock_getOwner** returned the error: 
**Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**

This is an attribute of edition two, but it can not generate exception if server is in edition one.

Can you check, please?

**Comment by mzillgith** [comment]
Thanks for the hint. The new patch should solve the issue.
