### ISSUE TITLE
[C#] ListOfVariable - Multiple data objects

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#88]
Hi Michael @mzillgith 

The method **MmsValue ReadValue (String objectReference, FunctionalConstraint fc)** allows to enter only one address (object reference). Until then, I was using reading by the logical node. However, a situation where the IED has an invalid data object may occur:

![image](https://user-images.githubusercontent.com/3512138/48440166-4e8c3e00-e76f-11e8-9ef4-4db6e868d30e.png)

**When I try to read the LN. I get (MMS_DATA_ACCESS_ERROR) (OBJECT_INVALIDATED):**

![image](https://user-images.githubusercontent.com/3512138/48440298-aa56c700-e76f-11e8-9b11-b2f64bab95f6.png)

![image](https://user-images.githubusercontent.com/3512138/48440305-b478c580-e76f-11e8-8800-4c4876bf43c3.png)

**Creating multiple data object requests is not performative. If it was possible to create a ListOfVariable request with list of data objects that I need. This registration error can be bypassed, because not all customers can fix this on IED. Request example (image of our current driver first edition):**

![image](https://user-images.githubusercontent.com/3512138/48440442-11747b80-e770-11e8-86be-3dc801678304.png)

![image](https://user-images.githubusercontent.com/3512138/48440513-3963df00-e770-11e8-905e-ff50d59e9f27.png)

**Could you analyse this implementation?**

**Comment by mzillgith** [comment]
Hi,
61850 doesn't specify reading a whole LN so I think some implementations will support it others not.
When I understood you correctly you want an API function that allows to send a single request with multiple variables?

Actually there are such API functions (see #50 ). They are just somewhat hidden. 

The problem is that it is not standard compliant reading multiple variables in a single request (see: https://iec61850.tissue-db.com/tissue/854). Even if most implementation may support it some others may not and probably this is also a problem for conformance certification (I am not sure about that yet).

A standard compliant way would be to create a data set with the required variables and then read the data set (or better use the data set with a report control block).

**Comment by IgorMundstein** [comment]
> Hi,
61850 doesn't specify reading a whole LN so I think some implementations will support it others not.

We have already done several tests and with multiple IEDs. None of the IEDs presented a problem requesting the logical node. On the contrary, this is extremely performative. If I have a logical node with 50 data objects. Instead of making 50 requests (one for each data object). All I need to do is just one request and your library handles it very well. Example:

![image](https://user-images.githubusercontent.com/3512138/48479634-090f5580-e7ef-11e8-9d8c-d7b00b5bb508.png)
![image](https://user-images.githubusercontent.com/3512138/48479647-13c9ea80-e7ef-11e8-9e31-c3cf426e97f0.png)

> When I understood you correctly you want an API function that allows to send a single request with multiple variables? Actually there are such API functions (see #50 ). They are just somewhat hidden.

Yes. The last two images I uploaded in the previous post. These are real images of our current driver running in an electrical substation. And it creates the requisition that way. These methods you mentioned allow this type of request? Could you publish these methods to the C# API?

> The problem is that it is not standard compliant reading multiple variables in a single request (see: https://iec61850.tissue-db.com/tissue/854). Even if most implementation may support it some others may not and probably this is also a problem for conformance certification (I am not sure about that yet). A standard compliant way would be to create a data set with the required variables and then read the data set (or better use the data set with a report control block).

I agree with you, but in the real world we know that not everything is perfect. Not always the owner of the IED has tools to edit the equipment configurations. The device does not always accept writing of new datasets or reports and returns access denied error.

We come across this situation. Where reading multiple data objects is impaired only because of a poorly formatted object. Unfortunately, MmsVariableSpecification does not provide information that the point is poorly formatted. Just when I try to read it, I get the data access error. In this case, it is necessary to circumvent the situation. If reading through the logical node is not possible, I need to have an alternative. As I said earlier, it is not performative to make requests for each data object.

The decision of how to read a point should not be from your API. This is an implementation we should do, but it would be essential for your API to provide this form of request.

**Comment by mzillgith** [comment]
Yes. This makes sense. I added a C# wrapper for the function to read multiple variables (MmsConnection.ReadMultipleVariables). Still keeping it in another API to indicate that it is not part of the IEC 61850 specification.

Here is an example how to use:
```
                MmsConnection mmsConnection = con.GetMmsConnection();

                MmsValue result = mmsConnection.ReadMultipleVariables("simpleIOGenericIO", new List<string>() {
                    "GGIO1$ST$Ind1", "GGIO1$ST$Ind1", "GGIO1$ST$Ind1","GGIO1$ST$Ind1"});
```

**Comment by IgorMundstein** [comment]
Thank you. 

ASAP I will test and give you a feedback.

**Comment by IgorMundstein** [comment]
It's worked. Thx!
