### ISSUE TITLE
SWIG. ClientReport object/InstallHandler 

### ISSUE THREAD

**Issue by Bubkagob** [mz-automation/libiec61850#9]
When I get reports using the C code from the client reporting example everything about works fine:
```
/* Configure the report receiver */
IedConnection_installReportHandler(con, 
                           "TEMPLATELD0/LLN0.BR.brcbMX0101", 
                            ClientReportControlBlock_getRptId(rcb), 
                            reportCallbackFunction,
                            (void*) dataSetDirectory);
```
But when I try to implement this example in for Python client --> I'm stucking in InstallReportHandler method:
```
iec61850.IedConnection_installReportHandler(con,
                                                "TEMPLATELD0/LLN0.BR.brcbMX0101",
                                                iec61850.ClientReportControlBlock_getRptId(rcb),
                                                MyCallbackFunction,
                                                dataSetDirectory
                                                )
```
and as a result of it is "Argument 4 of type  ReportCallBackFunction" exception from wrapper.cxx parsing part, 
If I use MyCallBackFunction() ---with brackets then It calls each time when IedConnection_installReportHandler calls

Issue.part 2:
as a result of it: In C-code it's easy to create and manipulate with ClientReport objects (from example too):

`void reportCallbackFunction(void* parameter, ClientReport report)`

but in iec61850.py there is only ClientReport methods that take this object as a parameter

If it not from issue-graded problem:
Can anyone provide any example for this "**InstallHandler** - **Receive** by event - **Create and Read** ClientReport object" chain

Thanks/Ivan

**Comment by hackerboygn** [comment]
@Bubkagob 
I have the same question about callback function, could I know your solution?

**Comment by Bubkagob** [comment]
@hackerboygn 
It is CTYPES solving:
First, add 
`
ClientReport ClientReport_FromInt(unsigned int addr); 
void IedConnection_installReportHandlerAddr(unsigned int addr, const char* rcbReference, const char* rptId, void (*handler)(void *, void *),  void* handlerParameter);
unsigned int IedConnection_ToAddress(IedConnection self);
` declarations into iec61850_client.h

and this

`
void IedConnection_installReportHandlerAddr(unsigned int addr, const char* rcbReference, const char* rptId, void (*handler)(void *, void *), void* handlerParameter)
{
  void * ptr = (void *)addr;
  IedConnection_installReportHandler(ptr, rcbReference, rptId, handler, handlerParameter);
}
`
and 
`
ClientReport ClientReport_FromInt(unsigned int addr)
{
  return (ClientReport)addr;
}
`

and

`
unsigned int IedConnection_ToAddress(IedConnection self)
{
  return (unsigned int)self;
}
`
 to client_report.c




and example code:

`
import os,sys
import iec61850
from ctypes import *

def test_func(param,ptr):
    print("Handler")
    print(type(ptr))
    print(ptr)
    report = iec61850.ClientReport_FromInt(ptr)
    mmsvalue = iec61850.ClientReport_getDataSetValues(report)
    print("Got report: " + str(iec61850.ClientReport_getRcbReference(report)))


if __name__=="__main__":
    print("Start")
    hostname="localhost"
    tcpPort=102
    con = iec61850.IedConnection_create()
    error = iec61850.IedConnection_connect(con, hostname, tcpPort)
    print(str(error))
    CB_PROTO=CFUNCTYPE(None, c_void_p, c_void_p)
    cbinst=CB_PROTO(test_func)
    val = c_int()
    #iec61850.IedConnection_installReportHandler(con,"111","111",cbinst, ctypes.byref(val)) 

    api=CDLL("/home/alexs/projects/libiec-dirty/debug/src/libiec61850-drt.so")
    ReportHandler=api.IedConnection_installReportHandlerAddr

    ReportHandler.argtypes=[c_uint, c_char_p, c_char_p, CB_PROTO, c_void_p]
    ReportHandler.restype = None

    addr=iec61850.IedConnection_ToAddress(con)
    
    rcb, error = iec61850.IedConnection_getRCBValues(con,"TEMPLATELD0/LLN0.BR.brcbMX0101", None)

    print("RCB:" + str(rcb))
    rid = iec61850.ClientReportControlBlock_getRptId(rcb)
    print("OriginalID: " + rid)

    rptRef=create_string_buffer(b"TEMPLATELD0/LLN0.BR.brcbMX0101") 
    rptID = create_string_buffer(b"TEMPLATELD0/LLN0$BR$brcbMX0101")
    ReportHandler(addr, rptRef,rptID, cbinst, None)

    print("Enabled: " + str(iec61850.ClientReportControlBlock_getRptEna(rcb)))
    
    
    iec61850.ClientReportControlBlock_setTrgOps(rcb, iec61850.TRG_OPT_DATA_UPDATE | iec61850.TRG_OPT_GI);
    iec61850.ClientReportControlBlock_setRptEna(rcb,True)
    error = iec61850.IedConnection_setRCBValues(con, rcb, iec61850.RCB_ELEMENT_RPT_ENA | iec61850.RCB_ELEMENT_TRG_OPS, True)

    print(error)
    input("Wait input....")
    iec61850.IedConnection_close(con)
    iec61850.IedConnection_destroy(con)
`
