### ISSUE TITLE
[C#] [Question] getVariableAccessAttributes PDU-SIZE overflow?

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#96]
Hi @mzillgith 

I'm using the trick **Connection.GetVariableSpecification(logicalNode.Address, FunctionalConstraint.NONE)** to get LN spec with all FC's and it has worked very well.

However, I came across a logical node that generated the error below. (Connected PDU-SIZE: 65000)

![image](https://user-images.githubusercontent.com/3512138/50091121-94667700-01f1-11e9-8588-aa3bc5b0494d.png)

![image](https://user-images.githubusercontent.com/3512138/50091201-d394c800-01f1-11e9-8915-3328056db704.png)

Unfortunately, the API threw an IedConnectionException with IedClientError **IED_ERROR_UNKNOWN** 

In that case, the correct would be create a request for each functional constraint? Is this a limitation of the IEC 61850 standard?

Example:
Connection.GetVariableSpecification(logicalNode.Address, FunctionalConstraint.ST);
Connection.GetVariableSpecification(logicalNode.Address, FunctionalConstraint.MX);

**Comment by mzillgith** [comment]
Hi, the answer means that the response would be too big to fit in a single MMS message. So you have to request smaller parts of the variable name space as you suggested. It is a limitation of the MMS protocol. Some services require that the whole response fits into a single response message.

**Comment by IgorMundstein** [comment]
Ok. Thx!
