### ISSUE TITLE
[C#] MmsValue (MmsType.MMS_INTEGER) Size() method

### ISSUE THREAD

**Issue by IgorMundstein** [mz-automation/libiec61850#97]
Hi @mzillgith 

I need to find out if an **MmsValue** of type **MMS_INTEGER** is an **Int32** or **Int64**

I tried to use Size() method to get size of integer in bits.

![image](https://user-images.githubusercontent.com/3512138/50104295-c63b0600-0210-11e9-9ea4-20e88313ee6e.png)

![image](https://user-images.githubusercontent.com/3512138/50104243-adcaeb80-0210-11e9-8f1c-525a5d563389.png)

![image](https://user-images.githubusercontent.com/3512138/50104272-bae7da80-0210-11e9-9453-5fd1ccfcd843.png)

**However, when I try to call it I get the MmsValueException**

![image](https://user-images.githubusercontent.com/3512138/50104348-ef5b9680-0210-11e9-8684-d8f1a5e04f8a.png)

![image](https://user-images.githubusercontent.com/3512138/50104320-d3f08b80-0210-11e9-9962-bce94562f14c.png)

**Would it be possible to implement something like this?**

![image](https://user-images.githubusercontent.com/3512138/50104869-4615a000-0212-11e9-9422-6b574beb49d5.png)

**Comment by mzillgith** [comment]
Hi,
MmsValue doesn't contain the required information. The size of MmsValue depends on the value. E.g. the value 1 will be encoded in one byte. The maximum size can be requested with the get variable specification service and you have to access the value with the MmsVariableSpecification_getSize function.

**Comment by IgorMundstein** [comment]
Ok. Thanks!
