### ISSUE TITLE
EntryID in server reporting

### ISSUE THREAD

**Issue by davideandreuzza** [mz-automation/libiec61850#98]
Hello,

Can you please clarify me whether the Optional Field entryID  is managed by the library or not, in server reporting?

In file `server/mms_mapping/reporting.c`, in function `sendReport` I found this comment that suggests that entryID is not sent:
```
 /* delete option fields for unsupported options */
    MmsValue_setBitStringBit(optFlds, 7, false); /* entryID */
    MmsValue_setBitStringBit(optFlds, 9, false); /* segmentation */
```
But in the same file, the entryID seems managed, for example in function `Reporting_RCBWriteAccessHandler`. 
Thanks

**Comment by mzillgith** [comment]
Hi,
entryID is managed. The sendReport function is only for unbuffered reporting. The entryID is only relevant for buffered reporting.

**Comment by davideandreuzza** [comment]
Thanks
